const PRODUCTS = [
  // MOZA Racing products
  { id: 'r3-bundle',    name: 'R3 Bundle',            brand: 'MOZA' },
  { id: 'r5-bundle',    name: 'R5 Bundle',            brand: 'MOZA' },
  { id: 'r9-bundle',    name: 'R9 Bundle',            brand: 'MOZA' },
  { id: 'r3-base',      name: 'R3 Wheel Base',        brand: 'MOZA' },
  { id: 'r5-base',      name: 'R5 Wheel Base',        brand: 'MOZA' },
  { id: 'r7-base',      name: 'R7 Wheel Base',        brand: 'MOZA' },
  { id: 'r9-base',      name: 'R9 Wheel Base',        brand: 'MOZA' },
  { id: 'r9-v3-base',   name: 'R9 V3 Wheel Base',     brand: 'MOZA' },
  { id: 'r11-base',     name: 'R11 Wheel Base',       brand: 'MOZA' },
  { id: 'r12-base',     name: 'R12 Wheel Base',       brand: 'MOZA' },
  { id: 'r16-base',     name: 'R16 Wheel Base',       brand: 'MOZA' },
  { id: 'r21-base',     name: 'R21 Wheel Base',       brand: 'MOZA' },
  { id: 'es-wheel',     name: 'ES Steering Wheel',    brand: 'MOZA' },
  { id: 'esx-wheel',    name: 'ESX Steering Wheel',   brand: 'MOZA' },
  { id: 'ks-wheel',     name: 'KS Steering Wheel',    brand: 'MOZA' },
  { id: 'ks-pro-wheel', name: 'KS Pro Steering Wheel',brand: 'MOZA' },
  { id: 'cs-wheel',     name: 'CS Steering Wheel',    brand: 'MOZA' },
  { id: 'cs-pro-wheel', name: 'CS Pro Steering Wheel',brand: 'MOZA' },
  { id: 'gs-wheel',     name: 'GS Steering Wheel',    brand: 'MOZA' },
  { id: 'gs-v2p-wheel', name: 'GS V2P Steering Wheel',brand: 'MOZA' },
  { id: 'rs-wheel',     name: 'RS Steering Wheel',    brand: 'MOZA' },
  { id: 'fsr2-wheel',   name: 'FSR2 Formula Wheel',   brand: 'MOZA' },
  { id: 'vision-gs',    name: 'Vision GS Wheel',      brand: 'MOZA' },
  { id: 'srp-pedals',   name: 'SR-P Pedals',          brand: 'MOZA' },
  { id: 'srp-lite',     name: 'SR-P Lite Pedals',     brand: 'MOZA' },
  { id: 'crp-pedals',   name: 'CRP Pedals',           brand: 'MOZA' },
  { id: 'crp2-pedals',  name: 'CRP2 Pedals',          brand: 'MOZA' },
  { id: 'hgp-shifter',  name: 'HGP Shifter',          brand: 'MOZA' },
  { id: 'handbrake',    name: 'Handbrake',            brand: 'MOZA' },
  { id: 'table-clamp',  name: 'Table Clamp',          brand: 'MOZA' },
  // MOZA Flight (飞模) products
  { id: 'ab6-bundle',   name: 'AB6 Flight Simulator', brand: '飞模' },
  { id: 'ab9-base',     name: 'AB9 FFB Base',         brand: '飞模' },
  { id: 'mhg-stick',    name: 'MHG Flightstick',      brand: '飞模' },
  { id: 'mh16-stick',   name: 'MH16 Flightstick',     brand: '飞模' },
  { id: 'ma3x-stick',   name: 'MA3X Side Stick',      brand: '飞模' },
  { id: 'ay210-yoke',   name: 'AY210 FFB Yoke Bundle',brand: '飞模' },
  { id: 'mtq-throttle', name: 'MTQ Throttle Quadrant',brand: '飞模' },
  { id: 'mtp-throttle', name: 'MTP Throttle',         brand: '飞模' },
  { id: 'mtlp-panel',   name: 'MTLP Panel',           brand: '飞模' },
  { id: 'mrp-pedals',   name: 'MRP Rudder Pedals',    brand: '飞模' },
];

const RETAILERS = [
  { id: 'bhphoto',     name: 'B&H Photo',         url: 'https://www.bhphotovideo.com',   country: 'US', currency: 'USD' },
  { id: 'microcenter', name: 'Micro Center',      url: 'https://www.microcenter.com',     country: 'US', currency: 'USD' },
  { id: 'simmotion-eu',name: 'Sim-Motion EU',     url: 'https://eu.sim-motion.com',       country: 'DE', currency: 'EUR' },
  { id: 'simmotion-us',name: 'Sim-Motion US',     url: 'https://us.sim-motion.com',       country: 'US', currency: 'USD' },
  { id: 'tracksvr',    name: 'TracksVR',          url: 'https://tracksvr.com',            country: 'IE', currency: 'USD' },
  { id: 'apexsim',     name: 'Apex Sim Racing',   url: 'https://www.apexsimracing.com',   country: 'US', currency: 'USD' },
  { id: 'ricmotech',   name: 'Ricmotech',         url: 'https://ricmotech.com',           country: 'US', currency: 'USD' },
  { id: 'gtomega',     name: 'GT Omega',          url: 'https://gtomegaracing.com',       country: 'GB', currency: 'GBP' },
  { id: 'pagnian',     name: 'Pagnian',           url: 'https://pagnian.com.au',          country: 'AU', currency: 'AUD' },
  { id: 'abruzzi',     name: 'Abruzzi',           url: 'https://www.abruzzi-official.co.uk', country: 'GB', currency: 'GBP' },
  { id: 'vr-hub',      name: 'Virtual Racing Hub', url: 'https://www.virtualracinghub.com', country: 'IN', currency: 'INR' },
  { id: 'noxgaming',   name: 'NOX Gaming',        url: 'https://noxgaming.ca',            country: 'CA', currency: 'CAD' },
  { id: 'kfire',       name: 'KFire Racing',      url: 'https://kfireracing.com.br',      country: 'BR', currency: 'BRL' },
];

const PRODUCT_URLS = {
  microcenter: {
    'r5-bundle': 'https://www.microcenter.com/product/682583/moza-r5-direct-drive-sim-racing-bundle',
    'r12-base':  'https://www.microcenter.com/product/682588/moza-r12-direct-drive-wheel-base',
  },
  'simmotion-eu': {
    'r9-v3-base': 'https://eu.sim-motion.com/moza-r9-v3-wheel-base',
    'ks-pro-wheel': 'https://eu.sim-motion.com/moza-ks-pro-steering-wheel',
    'gs-v2p-wheel': 'https://eu.sim-motion.com/moza-gs-v2p-steering-wheel',
    'cs-pro-wheel': 'https://eu.sim-motion.com/MOZA-CS-Pro-Lenkrad',
    'crp2-pedals': 'https://eu.sim-motion.com/moza-crp2-load-cell-pedals',
    'hgp-shifter': 'https://eu.sim-motion.com/moza-hgp-shifter',
    'handbrake': 'https://eu.sim-motion.com/moza-hbp-handbrake',
    'srp-pedals': 'https://eu.sim-motion.com/moza-srp-2-pedal-set',
  },
  tracksvr: {
    'r16-base': 'https://tracksvr.com/products/moza-r16-v2-wheel-base',
    'r21-base': 'https://tracksvr.com/collections/new-sim-racing-hardware/products/moza-r21-wheel-base-ultra',
    'cs-pro-wheel': 'https://tracksvr.com/products/moza-cs-pro-steering-wheel',
  },
  'simmotion-us': {
    'r3-bundle': 'https://us.sim-motion.com/products/moza-racing-r3-sim-racing-bundle',
    'r5-bundle': 'https://us.sim-motion.com/products/moza-racing-r5-sim-racing-bundle',
    'r12-base': 'https://us.sim-motion.com/products/moza-racing-r12-v2-direct-drive-base',
    'ks-wheel': 'https://us.sim-motion.com/products/moza-racing-ks-steering-wheel',
    'cs-wheel': 'https://us.sim-motion.com/products/moza-racing-cs-v2p-steering-wheel',
    'rs-wheel': 'https://us.sim-motion.com/products/moza-racing-rs-gt-wheel',
    'crp2-pedals': 'https://us.sim-motion.com/products/moza-racing-crp2-pedals',
    'srp-pedals': 'https://us.sim-motion.com/products/moza-racing-srp-pedals',
    'hgp-shifter': 'https://us.sim-motion.com/products/moza-racing-hgp-shifter',
    'handbrake': 'https://us.sim-motion.com/products/moza-racing-hbp-handbrake',
  },
  ricmotech: {
    'r12-base': 'https://www.ricmotech.com/moza-r12-.html',
    'r16-base': 'https://www.ricmotech.com/moza-r16-direct-drive-wheel-base.html',
    'r21-base': 'https://www.ricmotech.com/MOZA-R21-Direct-Drive-Wheelbase_p_613.html',
    'ks-wheel': 'https://www.ricmotech.com/moza-ks-steering-wheel.html',
    'gs-v2p-wheel': 'https://www.ricmotech.com/MOZA-GS-V2P-Steering-Wheel_p_652.html',
    'cs-wheel': 'https://www.ricmotech.com/moza-cs-v2-steering-wheel.html',
    'fsr2-wheel': 'https://www.ricmotech.com/moza-fsr-steering-wheel.html',
    'srp-pedals': 'https://www.ricmotech.com/moza-sr-p-pedal.html',
    'crp2-pedals': 'https://www.ricmotech.com/-MOZA-CRP2-Throttle-and-Brake-Pedals_p_715.html',
  },
  noxgaming: {
    'r3-bundle': 'https://www.noxgaming.ca/product/moza-r3-bundle-steering-wheel-pedals-wheelbase-xbox-pc/',
    'r12-base': 'https://www.noxgaming.ca/product/moza-r12-v2-wheelbase/',
    'r21-base': 'https://www.noxgaming.ca/product/moza-r21-v2-direct-drive-wheelbase/',
    'cs-pro-wheel': 'https://www.noxgaming.ca/product/moza-cs-pro-round-sim-racing-steering-wheel/',
    'ks-pro-wheel': 'https://www.noxgaming.ca/product/moza-ks-pro-steering-wheel/',
  },
  abruzzi: {
    'r5-bundle': 'https://www.abruzzi-official.co.uk/shop/sim-racing/moza-bundles/moza-r5-bundle-dd-r5-wheelbase-es-steering-wheel-sr-p-lite-pedals-r5-table-clamp/',
    'r9-v3-base': 'https://www.abruzzi-official.co.uk/shop/sim-racing/moza-wheelbases/moza-r9-v3-direct-drive-wheelbase/',
    'r12-base': 'https://www.abruzzi-official.co.uk/shop/sim-racing/moza-wheelbases/moza-r12-v2-wheelbase/',
    'r21-base': 'https://www.abruzzi-official.co.uk/shop/sim-racing/moza-wheelbases/moza-r21-ultra-wheelbase/',
    'esx-wheel': 'https://www.abruzzi-official.co.uk/shop/sim-racing/moza-wheels/moza-esx-steering-wheel-for-xbox/',
    'ks-wheel': 'https://www.abruzzi-official.co.uk/shop/sim-racing/moza-wheels/ks-wheel/',
    'ks-pro-wheel': 'https://www.abruzzi-official.co.uk/shop/sim-racing/moza-wheels/moza-ks-pro-wheel/',
    'cs-wheel': 'https://www.abruzzi-official.co.uk/shop/sim-racing/moza-wheels/moza-cs-v2p-round-wheel/',
    'cs-pro-wheel': 'https://www.abruzzi-official.co.uk/shop/sim-racing/moza-wheels/moza-cs-pro-wheel/',
    'gs-v2p-wheel': 'https://www.abruzzi-official.co.uk/shop/sim-racing/moza-wheels/moza-gs-v2p-steering-wheel/',
    'rs-wheel': 'https://www.abruzzi-official.co.uk/shop/sim-racing/moza-wheels/moza-rs-v2-sterring-wheel/',
    'fsr2-wheel': 'https://www.abruzzi-official.co.uk/shop/sim-racing/moza-wheels/moza-fsr2-wheel/',
    'srp-pedals': 'https://www.abruzzi-official.co.uk/shop/sim-racing/moza-pedals/srp2-load-cell-pedals/',
    'crp2-pedals': 'https://www.abruzzi-official.co.uk/shop/sim-racing/moza-pedals/moza-crp2-pedals/',
    'hgp-shifter': 'https://www.abruzzi-official.co.uk/shop/sim-racing/sim-racing-accessories/moza-hgp-h-pattern-shifter/',
    'handbrake': 'https://www.abruzzi-official.co.uk/shop/sim-racing/sim-racing-accessories/mozahbphandbrake/',
    'table-clamp': 'https://www.abruzzi-official.co.uk/shop/sim-racing/sim-racing-accessories/moza-r9-r12-r16-r21-table-mounting-bracket/',
  },
  gtomega: {
    'r3-bundle': 'https://www.gtomega.co.uk/products/moza-racing-r3-bundle',
    'r5-bundle': 'https://www.gtomega.co.uk/products/moza-r5-bundle-kit',
    'r9-v3-base': 'https://www.gtomega.co.uk/products/moza-r9-wheel-base',
    'r12-base': 'https://www.gtomega.co.uk/products/moza-racing-r12-wheel-base',
    'r21-base': 'https://www.gtomega.co.uk/products/moza-r21-ultra',
    'esx-wheel': 'https://www.gtomega.co.uk/products/moza-racing-esx-steering-wheel-for-pc-xbox',
    'ks-wheel': 'https://www.gtomega.co.uk/products/moza-racing-ks-steering-wheel',
    'ks-pro-wheel': 'https://www.gtomega.co.uk/products/moza-ks-pro-wheel',
    'cs-wheel': 'https://www.gtomega.co.uk/products/moza-cs-wheel-v2p',
    'cs-pro-wheel': 'https://www.gtomega.co.uk/products/moza-cs-pro-wheel',
    'gs-v2p-wheel': 'https://www.gtomega.co.uk/products/moza-racing-gs-v2p-gt-wheel',
    'rs-wheel': 'https://www.gtomega.co.uk/products/moza-racing-rs-wheel',
    'fsr2-wheel': 'https://www.gtomega.co.uk/products/moza-fsr2-wheel',
    'srp-pedals': 'https://www.gtomega.co.uk/products/moza-srp-two-pedals',
    'crp2-pedals': 'https://www.gtomega.co.uk/products/moza-racing-crp2-pedals',
    'hgp-shifter': 'https://www.gtomega.co.uk/products/moza-racing-hgp-shifter',
    'handbrake': 'https://www.gtomega.co.uk/products/moza-racing-hbp-handbrake',
    'table-clamp': 'https://www.gtomega.co.uk/products/r9-table-clamp',
  },
  apexsim: {
    'r9-v3-base': 'https://www.apexsimracing.com/products/moza-racing-r9-v3-wheel-base-9nm',
    'r12-base': 'https://www.apexsimracing.com/products/moza-racing-r12-wheel-base-12nm',
    'r21-base': 'https://www.apexsimracing.com/collections/sim-racing-direct-drive-wheel-bases/products/moza-racing-r21-ultra-wheelbase-21nm',
    'cs-pro-wheel': 'https://www.apexsimracing.com/products/moza-cs-pro-steering-wheel',
    'ks-pro-wheel': 'https://www.apexsimracing.com/collections/moza-racing-steering-wheels/products/moza-ks-pro-steering-wheel',
    'crp2-pedals': 'https://www.apexsimracing.com/products/moza-racing-crp2-load-cell-pedals',
    'fsr2-wheel': 'https://www.apexsimracing.com/products/moza-racing-fsr2-formula-wheel',
    'esx-wheel': 'https://www.apexsimracing.com/products/moza-racing-esx-steering-wheel',
    'rs-wheel': 'https://www.apexsimracing.com/products/moza-racing-rs-v2-steering-wheel',
  },
  kfire: {
    'r9-v3-base': 'https://www.kfireracing.com.br/base-moza-r9-v2/p',
    'r12-base': 'https://www.kfireracing.com.br/base-moza-r12/p',
    'r21-base': 'https://www.kfireracing.com.br/base-moza-r21-671a8afb04544/p',
    'ks-wheel': 'https://www.kfireracing.com.br/volante-moza-ks/p',
    'gs-v2p-wheel': 'https://www.kfireracing.com.br/volante-moza-gs-v2/p',
    'fsr2-wheel': 'https://www.kfireracing.com.br/volante-moza-fsr2-formula/p',
    'srp-pedals': 'https://www.kfireracing.com.br/pedal-srp/p',
    'crp2-pedals': 'https://www.kfireracing.com.br/pedal-moza-crp2/p',
    'handbrake': 'https://www.kfireracing.com.br/freio-de-mao-moza-hbp/p',
  },
  pagnian: {
    'r3-bundle': 'https://pagnianimports.com.au/products/moza-r3-bundle-for-pc',
    'r5-bundle': 'https://pagnianimports.com.au/products/moza-steering-wheel-r5',
    'r9-v3-base': 'https://pagnianimports.com.au/products/moza-r9-v3-direct-drive-wheel-base',
    'r12-base': 'https://pagnianimports.com.au/products/moza-r12-v2-direct-drive-wheelbase',
    'r16-base': 'https://pagnianimports.com.au/products/moza-r16-v2-direct-drive-wheel-base',
    'r21-base': 'https://pagnianimports.com.au/products/moza-r21-v2-direct-drive-wheel-base',
    'esx-wheel': 'https://pagnianimports.com.au/products/moza-esx',
    'ks-wheel': 'https://pagnianimports.com.au/products/moza-ks-steering-wheel',
    'ks-pro-wheel': 'https://pagnianimports.com.au/products/moza-ks-pro-steering-wheel',
    'cs-wheel': 'https://pagnianimports.com.au/products/moza-cs-v2p-steering-wheel',
    'cs-pro-wheel': 'https://pagnianimports.com.au/products/moza-cs-pro-steering-wheel',
    'gs-v2p-wheel': 'https://pagnianimports.com.au/products/moza-gs-v2p-steering-wheel-microfiber-leather-version',
    'rs-wheel': 'https://pagnianimports.com.au/products/moza-rs-racing-wheel-round-leather',
    'fsr2-wheel': 'https://pagnianimports.com.au/products/moza-fsr2-formula-wheel',
    'srp-pedals': 'https://pagnianimports.com.au/products/moza-srp-pedal',
    'crp2-pedals': 'https://pagnianimports.com.au/products/moza-crp2-pedals-throttle-brake',
    'hgp-shifter': 'https://pagnianimports.com.au/products/moza-hgp-shifter',
    'handbrake': 'https://pagnianimports.com.au/products/moza-hbp-handbrake',
    'table-clamp': 'https://pagnianimports.com.au/products/moza-table-clamp-for-r9-wheel-base',
  },
  'vr-hub': {
    'r3-bundle': 'https://www.virtualracinghub.com/products/moza-r3-bundle',
    'r5-bundle': 'https://www.virtualracinghub.com/products/moza-r5-bundle-in-india',
    'r9-v3-base': 'https://www.virtualracinghub.com/products/moza-racing-r9-v3',
    'r12-base': 'https://www.virtualracinghub.com/products/moza-racing-r12v2',
    'r16-base': 'https://www.virtualracinghub.com/products/moza-r16-v2-direct-drive-wheel-base',
    'r21-base': 'https://www.virtualracinghub.com/products/moza-r21-ultra',
    'esx-wheel': 'https://www.virtualracinghub.com/products/es-steering-wheel-india',
    'ks-wheel': 'https://www.virtualracinghub.com/products/moza-racing-ks-wheel-india',
    'ks-pro-wheel': 'https://www.virtualracinghub.com/products/moza-ks-pro-steering-wheel',
    'cs-wheel': 'https://www.virtualracinghub.com/products/moza-racing-cs-steering-wheel',
    'cs-pro-wheel': 'https://www.virtualracinghub.com/products/moza-cs-pro-steering-wheel',
    'gs-v2p-wheel': 'https://www.virtualracinghub.com/products/moza-racing-gs-wheel-india',
    'rs-wheel': 'https://www.virtualracinghub.com/products/rs-v2-steering-wheel-india',
    'fsr2-wheel': 'https://www.virtualracinghub.com/products/moza-fsr2-formula-wheel',
    'crp2-pedals': 'https://www.virtualracinghub.com/products/moza-crp2-pedals',
    'hgp-shifter': 'https://www.virtualracinghub.com/products/moza-hgp-shifter-india',
    'handbrake': 'https://www.virtualracinghub.com/products/moza-hbp-handbrake-india',
    'table-clamp': 'https://www.virtualracinghub.com/products/moza-table-fixed-clamp-india',
  },
  // MOZA Flight (飞模) product URLs
  gtomega: {
    'ab9-base':     'https://www.gtomega.co.uk/products/moza-flight-ab9-base',
    'mh16-stick':   'https://www.gtomega.co.uk/products/moza-flight-mh16-flightstick',
    'mtp-throttle': 'https://www.gtomega.co.uk/products/moza-flight-mtp-throttle-panel',
    'mtq-throttle': 'https://www.gtomega.co.uk/products/moza-mtq-throttle-panel',
    'mtlp-panel':   'https://www.gtomega.co.uk/products/moza-flight-mtp-take-off-panel',
  },
  pagnian: {
    'ab6-bundle':   'https://pagnianimports.com.au/products/moza-ab6-flight-simulator',
    'mh16-stick':   'https://pagnianimports.com.au/products/moza-mh16-flightstick',
  },
  'simmotion-us': {
    'ab9-base':     'https://us.sim-motion.com/products/moza-flight-ab9-base',
  },
};

function buildUrlEntries() {
  var entries = [];
  for (var retailerId in PRODUCT_URLS) {
    var products = PRODUCT_URLS[retailerId];
    for (var productId in products) {
      entries.push({ url: products[productId], retailerId: retailerId, productId: productId });
    }
  }
  return entries;
}

// MSRP in USD from MOZA official store (mozaracing.com)
const MSRP_MAP = {
  // MOZA Racing
  'r3-bundle':    349,
  'r5-bundle':    599,
  'r9-bundle':    799,
  'r9-v3-base':   499,
  'r12-base':     499,
  'r16-base':     659,
  'r21-base':     999,
  'es-wheel':     99,
  'esx-wheel':    149,
  'ks-wheel':     199,
  'ks-pro-wheel': 349,
  'cs-wheel':     249,
  'cs-pro-wheel': 349,
  'gs-v2p-wheel': 399,
  'rs-wheel':     399,
  'fsr2-wheel':   599,
  'vision-gs':    699,
  'srp-lite':     79,
  'srp-pedals':   199,
  'crp-pedals':   349,
  'crp2-pedals':  399,
  'hgp-shifter':  159,
  'handbrake':    109,
  'table-clamp':  49,
  // MOZA Flight (飞模)
  'ab6-bundle':   399,
  'ab9-base':     549,
  'mhg-stick':    99,
  'mh16-stick':   169,
  'ma3x-stick':   79,
  'ay210-yoke':   848,
  'mtq-throttle': 199,
  'mtp-throttle': 329,
  'mtlp-panel':   149,
  'mrp-pedals':   349,
};

module.exports = { PRODUCTS, RETAILERS, PRODUCT_URLS, MSRP_MAP, buildUrlEntries };
