const PRODUCTS = [
  // MOZA Racing products
  { id: 'r3-bundle',    name: 'R3 Bundle',            brand: 'Moza RS21' },
  { id: 'r5-bundle',    name: 'R5 Bundle',            brand: 'Moza RS21' },
  { id: 'r9-bundle',    name: 'R9 Bundle',            brand: 'Moza RS21' },
  { id: 'r3-base',      name: 'R3 Wheel Base',        brand: 'Moza RS21' },
  { id: 'r5-base',      name: 'R5 Wheel Base',        brand: 'Moza RS21' },
  { id: 'r7-base',      name: 'R7 Wheel Base',        brand: 'Moza RS21' },
  { id: 'r9-base',      name: 'R9 Wheel Base',        brand: 'Moza RS21' },
  { id: 'r9-v3-base',   name: 'R9 V3 Wheel Base',     brand: 'Moza RS21' },
  { id: 'r11-base',     name: 'R11 Wheel Base',       brand: 'Moza RS21' },
  { id: 'r12-base',     name: 'R12 Wheel Base',       brand: 'Moza RS21' },
  { id: 'r16-base',     name: 'R16 Wheel Base',       brand: 'Moza RS21' },
  { id: 'r21-base',     name: 'R21 Wheel Base',       brand: 'Moza RS21' },
  { id: 'es-wheel',     name: 'ES Steering Wheel',    brand: 'Moza RS21' },
  { id: 'esx-wheel',    name: 'ESX Steering Wheel',   brand: 'Moza RS21' },
  { id: 'ks-wheel',     name: 'KS Steering Wheel',    brand: 'Moza RS21' },
  { id: 'ks-pro-wheel', name: 'KS Pro Steering Wheel',brand: 'Moza RS21' },
  { id: 'cs-wheel',     name: 'CS Steering Wheel',    brand: 'Moza RS21' },
  { id: 'cs-pro-wheel', name: 'CS Pro Steering Wheel',brand: 'Moza RS21' },
  { id: 'gs-wheel',     name: 'GS Steering Wheel',    brand: 'Moza RS21' },
  { id: 'gs-v2p-wheel', name: 'GS V2P Steering Wheel',brand: 'Moza RS21' },
  { id: 'rs-wheel',     name: 'RS Steering Wheel',    brand: 'Moza RS21' },
  { id: 'fsr2-wheel',   name: 'FSR2 Formula Wheel',   brand: 'Moza RS21' },
  { id: 'vision-gs',    name: 'Vision GS Wheel',      brand: 'Moza RS21' },
  { id: 'srp-pedals',   name: 'SR-P Pedals',          brand: 'Moza RS21' },
  { id: 'srp-lite',     name: 'SR-P Lite Pedals',     brand: 'Moza RS21' },
  { id: 'crp-pedals',   name: 'CRP Pedals',           brand: 'Moza RS21' },
  { id: 'crp2-pedals',  name: 'CRP2 Pedals',          brand: 'Moza RS21' },
  { id: 'hgp-shifter',  name: 'HGP Shifter',          brand: 'Moza RS21' },
  { id: 'handbrake',    name: 'Handbrake',            brand: 'Moza RS21' },
  { id: 'table-clamp',  name: 'Table Clamp',          brand: 'Moza RS21' },
  // MOZA Flight (飞模) products
  { id: 'ab6-bundle',   name: 'AB6 Flight Simulator', brand: 'Moza AS23' },
  { id: 'ab9-base',     name: 'AB9 FFB Base',         brand: 'Moza AS23' },
  { id: 'mhg-stick',    name: 'MHG Flightstick',      brand: 'Moza AS23' },
  { id: 'mh16-stick',   name: 'MH16 Flightstick',     brand: 'Moza AS23' },
  { id: 'ma3x-stick',   name: 'MA3X Side Stick',      brand: 'Moza AS23' },
  { id: 'ay210-yoke',   name: 'AY210 FFB Yoke Bundle',brand: 'Moza AS23' },
  { id: 'mtq-throttle', name: 'MTQ Throttle Quadrant',brand: 'Moza AS23' },
  { id: 'mtp-throttle', name: 'MTP Throttle',         brand: 'Moza AS23' },
  { id: 'mtlp-panel',   name: 'MTLP Panel',           brand: 'Moza AS23' },
  { id: 'mrp-pedals',   name: 'MRP Rudder Pedals',    brand: 'Moza AS23' },
];

const RETAILERS = [
  { id: 'bhphoto',     name: 'B&H Photo',         url: 'https://www.bhphotovideo.com',   country: 'US', currency: 'USD' },
  { id: 'microcenter', name: 'Micro Center',      url: 'https://www.microcenter.com',     country: 'US', currency: 'USD' },
  { id: 'simmotion-eu',name: 'Sim-Motion EU',     url: 'https://eu.sim-motion.com',       country: 'DE', currency: 'EUR' },
  { id: 'simmotion-us',name: 'Sim-Motion US',     url: 'https://us.sim-motion.com',       country: 'US', currency: 'USD' },
  { id: 'tracksvr',    name: 'TracksVR',          url: 'https://tracksvr.com',            country: 'IE', currency: 'USD' },
  { id: 'apexsim',     name: 'Apex Sim Racing',   url: 'https://www.apexsimracing.com',   country: 'US', currency: 'USD' },
  { id: 'ricmotech',   name: 'Ricmotech',         url: 'https://ricmotech.com',           country: 'US', currency: 'USD' },
  { id: 'gtomega',     name: 'GT Omega',          url: 'https://gtomegaracing.com',       country: 'GB', currency: 'GBP' },
  { id: 'pagnian',     name: 'Pagnian',           url: 'https://pagnian.com.au',          country: 'AU', currency: 'AUD' },
  { id: 'abruzzi',     name: 'Abruzzi',           url: 'https://www.abruzzi-official.co.uk', country: 'GB', currency: 'GBP' },
  { id: 'vr-hub',      name: 'Virtual Racing Hub', url: 'https://www.virtualracinghub.com', country: 'IN', currency: 'INR' },
  { id: 'noxgaming',   name: 'NOX Gaming',        url: 'https://noxgaming.ca',            country: 'CA', currency: 'CAD' },
  { id: 'kfire',       name: 'KFire Racing',      url: 'https://kfireracing.com.br',      country: 'BR', currency: 'BRL' },
  { id: 'simufy',      name: 'Simufy',            url: 'https://simufy.com',               country: 'ES', currency: 'EUR' },
  { id: 'son-video',   name: 'Son-Video',          url: 'https://www.son-video.com',        country: 'FR', currency: 'EUR' },
  { id: 'caseking',    name: 'Caseking',           url: 'https://www.caseking.de',          country: 'DE', currency: 'EUR' },
  { id: 'gomotorsports', name: 'GO Motorsports',   url: 'https://gomotorsportsshop.com',    country: 'US', currency: 'USD' },
  { id: 'simracingpros',name: 'Sim Racing Pros',   url: 'https://www.simracingpros.com',    country: 'US', currency: 'USD' },
  { id: 'racegear',     name: 'RaceGear',           url: 'https://www.racegear.eu',          country: 'NL', currency: 'EUR' },
  { id: 'electronicscrazy', name: 'ElectronicsCrazy', url: 'https://www.electronicscrazy.sg', country: 'SG', currency: 'SGD' },
  { id: 'demontweeks',     name: 'Demon Tweeks',        url: 'https://www.demon-tweeks.com',         country: 'GB', currency: 'GBP' },
  { id: 'advancedsimracing', name: 'Advanced Sim Racing', url: 'https://www.advancedsimracing.com',   country: 'CA', currency: 'CAD' },
  { id: 'maxgaming',       name: 'MaxGaming',            url: 'https://www.maxgaming.se',             country: 'SE', currency: 'EUR' },
  { id: 'simline',         name: 'Simline',              url: 'https://simline.eu',                   country: 'PL', currency: 'EUR' },
  { id: 'simracewebshop',  name: 'SimRace Webshop',      url: 'https://www.simracewebshop.com',        country: 'NL', currency: 'EUR' },
  { id: 'gamergeardirect', name: 'Gamer Gear Direct',    url: 'https://www.gamergeardirect.com.au',    country: 'AU', currency: 'AUD' },
  { id: 'player1simgear',  name: 'Player1 Sim Gear',     url: 'https://www.p1simgear.com.au',          country: 'AU', currency: 'AUD' },
  { id: 'thegamesmen',     name: 'The Gamesmen',         url: 'https://www.gamesmen.com.au',           country: 'AU', currency: 'AUD' },
  { id: 'jbhifi',          name: 'JB Hi-Fi',             url: 'https://www.jbhifi.com.au',             country: 'AU', currency: 'AUD' },
  { id: 'alternate',       name: 'Alternate',            url: 'https://www.alternate.de',              country: 'DE', currency: 'EUR' },
  { id: 'kjellcompany',    name: 'Kjell & Company',      url: 'https://www.kjell.com',                 country: 'SE', currency: 'SEK' },
  // Batch 2: High-value dealers (May 2026)
  { id: 'overclockersuk',  name: 'Overclockers UK',      url: 'https://www.overclockers.co.uk',         country: 'GB', currency: 'GBP' },
  { id: 's5tech',          name: 'S5 Technology',        url: 'https://s5tech.cc',                     country: 'SG', currency: 'SGD' },
  { id: 'simsolution',     name: 'SimSolution',          url: 'https://www.simsolution.co.il',          country: 'IL', currency: 'ILS' },
  { id: 'simracingstore',  name: 'SimRacing Store',      url: 'https://www.simracingstore.cl',          country: 'CL', currency: 'CLP' },
  { id: 'speednation',     name: 'Speednation',          url: 'https://speednation.co.nz',              country: 'NZ', currency: 'NZD' },
  { id: 'befastracing',    name: 'Be Fast Racing',       url: 'https://www.befastracing.com',           country: 'MX', currency: 'USD' },
  { id: 'simking',         name: 'SimKing',              url: 'https://simking.eu',                     country: 'FR', currency: 'EUR' },
  { id: 'simhubpro',       name: 'SIMHUB.PRO',           url: 'https://simhub.pro',                     country: 'PL', currency: 'PLN' },
  { id: 'milestone',       name: 'Milestone Japan',      url: 'https://www.milestone-net.co.jp',        country: 'JP', currency: 'JPY' },
  { id: 'mozakorea',       name: 'MOZA Korea',           url: 'https://mozaracing.co.kr',               country: 'KR', currency: 'KRW' },
  { id: 'simulatorcave',   name: 'Simulator Cave',       url: 'https://simulatorcave.com',              country: 'ZA', currency: 'ZAR' },
  { id: 'sdeal',           name: 'SDeal',                url: 'https://www.sdeal.com.my',               country: 'MY', currency: 'MYR' },
  { id: 'yoho',            name: 'YOHO 友和',             url: 'https://www.yohohongkong.com',           country: 'HK', currency: 'HKD' },
  { id: 'pchome',          name: 'PChome 24h',           url: 'https://24h.pchome.com.tw',              country: 'TW', currency: 'TWD' },
  { id: 'delenordic',      name: 'DELE Nordic',          url: 'https://www.delenordic.com',             country: 'DK', currency: 'DKK' },
  // Batch 3: New dealers (May 2026)
  { id: 'simracer',        name: 'SimRacer Austria',      url: 'https://simracer.at',                          country: 'AT', currency: 'EUR' },
  { id: 'simultimate',     name: 'SimUltimate',            url: 'https://simultimate.ch',                      country: 'CH', currency: 'CHF' },
  { id: 'arcteam',         name: 'ARC-Team Italy',         url: 'https://moza.arc-team.it',                    country: 'IT', currency: 'EUR' },
  // Batch 4: New dealers (May 2026) — previously Instagram-only
  { id: 'focussimracing',  name: 'Focus Sim Racing',       url: 'https://focussimracing.com',                  country: 'US', currency: 'USD' },
  { id: 'vipcbuilder',     name: 'VI PC Builder & Games',  url: 'https://vipcbuilder.ca',                      country: 'CA', currency: 'CAD' },
  { id: 'pitlanesimracing',name: 'Pit Lane Sim Racing',    url: 'https://pitlanesimracing.com',                country: 'CA', currency: 'CAD' },
  // Batch 5: Philippine expansion (May 2026)
  { id: 'gameone',         name: 'Game One PH',            url: 'https://gameone.ph',                          country: 'PH', currency: 'PHP' },
  // Batch 6: SE Asia & global expansion (May 2026)
  { id: 'thinkofsim',      name: 'Think of Sim',           url: 'https://www.thinkofsim.com',                  country: 'TH', currency: 'THB' },
  { id: 'ggksimracing',    name: 'GGK Simracing',          url: 'https://guidegamingkits.com',                 country: 'TH', currency: 'THB' },
  { id: 'simracingstore',  name: 'SimRacing Store',        url: 'https://www.simracingstore.cl',               country: 'CL', currency: 'CLP' },
  { id: 'megabikeplus',    name: 'Megabike Plus',          url: 'https://www.megabikeplus.cz',                 country: 'CZ', currency: 'CZK' },
];

const PRODUCT_URLS = {
  microcenter: {
    'r5-bundle': 'https://www.microcenter.com/product/682583/moza-r5-direct-drive-sim-racing-bundle',
    'r12-base':  'https://www.microcenter.com/product/682588/moza-r12-direct-drive-wheel-base',
  },
  'simmotion-eu': {
    'r9-v3-base': 'https://eu.sim-motion.com/moza-r9-v3-wheel-base',
    'ks-pro-wheel': 'https://eu.sim-motion.com/moza-ks-pro-steering-wheel',
    'gs-v2p-wheel': 'https://eu.sim-motion.com/moza-gs-v2p-steering-wheel',
    'cs-pro-wheel': 'https://eu.sim-motion.com/MOZA-CS-Pro-Lenkrad',
    'crp2-pedals': 'https://eu.sim-motion.com/moza-crp2-load-cell-pedals',
    'hgp-shifter': 'https://eu.sim-motion.com/moza-hgp-shifter',
    'handbrake': 'https://eu.sim-motion.com/moza-hbp-handbrake',
    'srp-pedals': 'https://eu.sim-motion.com/moza-srp-2-pedal-set',
  },
  tracksvr: {
    'r16-base': 'https://tracksvr.com/products/moza-r16-v2-wheel-base',
    'r21-base': 'https://tracksvr.com/collections/new-sim-racing-hardware/products/moza-r21-wheel-base-ultra',
    'cs-pro-wheel': 'https://tracksvr.com/products/moza-cs-pro-steering-wheel',
  },
  'simmotion-us': {
    'r3-bundle': 'https://us.sim-motion.com/products/moza-racing-r3-sim-racing-bundle',
    'r5-bundle': 'https://us.sim-motion.com/products/moza-racing-r5-sim-racing-bundle',
    'r12-base': 'https://us.sim-motion.com/products/moza-racing-r12-v2-direct-drive-base',
    'ks-wheel': 'https://us.sim-motion.com/products/moza-racing-ks-steering-wheel',
    'cs-wheel': 'https://us.sim-motion.com/products/moza-racing-cs-v2p-steering-wheel',
    'rs-wheel': 'https://us.sim-motion.com/products/moza-racing-rs-gt-wheel',
    'crp2-pedals': 'https://us.sim-motion.com/products/moza-racing-crp2-pedals',
    'srp-pedals': 'https://us.sim-motion.com/products/moza-racing-srp-pedals',
    'hgp-shifter': 'https://us.sim-motion.com/products/moza-racing-hgp-shifter',
    'handbrake': 'https://us.sim-motion.com/products/moza-racing-hbp-handbrake',
  },
  ricmotech: {
    'r12-base': 'https://www.ricmotech.com/moza-r12-.html',
    'r16-base': 'https://www.ricmotech.com/moza-r16-direct-drive-wheel-base.html',
    'r21-base': 'https://www.ricmotech.com/MOZA-R21-Direct-Drive-Wheelbase_p_613.html',
    'ks-wheel': 'https://www.ricmotech.com/moza-ks-steering-wheel.html',
    'gs-v2p-wheel': 'https://www.ricmotech.com/MOZA-GS-V2P-Steering-Wheel_p_652.html',
    'cs-wheel': 'https://www.ricmotech.com/moza-cs-v2-steering-wheel.html',
    'fsr2-wheel': 'https://www.ricmotech.com/moza-fsr-steering-wheel.html',
    'srp-pedals': 'https://www.ricmotech.com/moza-sr-p-pedal.html',
    'crp2-pedals': 'https://www.ricmotech.com/-MOZA-CRP2-Throttle-and-Brake-Pedals_p_715.html',
  },
  noxgaming: {
    'r3-bundle': 'https://www.noxgaming.ca/product/moza-r3-bundle-steering-wheel-pedals-wheelbase-xbox-pc/',
    'r12-base': 'https://www.noxgaming.ca/product/moza-r12-v2-wheelbase/',
    'r21-base': 'https://www.noxgaming.ca/product/moza-r21-v2-direct-drive-wheelbase/',
    'cs-pro-wheel': 'https://www.noxgaming.ca/product/moza-cs-pro-round-sim-racing-steering-wheel/',
    'ks-pro-wheel': 'https://www.noxgaming.ca/product/moza-ks-pro-steering-wheel/',
  },
  abruzzi: {
    'r5-bundle': 'https://www.abruzzi-official.co.uk/shop/sim-racing/moza-bundles/moza-r5-bundle-dd-r5-wheelbase-es-steering-wheel-sr-p-lite-pedals-r5-table-clamp/',
    'r9-v3-base': 'https://www.abruzzi-official.co.uk/shop/sim-racing/moza-wheelbases/moza-r9-v3-direct-drive-wheelbase/',
    'r12-base': 'https://www.abruzzi-official.co.uk/shop/sim-racing/moza-wheelbases/moza-r12-v2-wheelbase/',
    'r21-base': 'https://www.abruzzi-official.co.uk/shop/sim-racing/moza-wheelbases/moza-r21-ultra-wheelbase/',
    'esx-wheel': 'https://www.abruzzi-official.co.uk/shop/sim-racing/moza-wheels/moza-esx-steering-wheel-for-xbox/',
    'ks-wheel': 'https://www.abruzzi-official.co.uk/shop/sim-racing/moza-wheels/ks-wheel/',
    'ks-pro-wheel': 'https://www.abruzzi-official.co.uk/shop/sim-racing/moza-wheels/moza-ks-pro-wheel/',
    'cs-wheel': 'https://www.abruzzi-official.co.uk/shop/sim-racing/moza-wheels/moza-cs-v2p-round-wheel/',
    'cs-pro-wheel': 'https://www.abruzzi-official.co.uk/shop/sim-racing/moza-wheels/moza-cs-pro-wheel/',
    'gs-v2p-wheel': 'https://www.abruzzi-official.co.uk/shop/sim-racing/moza-wheels/moza-gs-v2p-steering-wheel/',
    'rs-wheel': 'https://www.abruzzi-official.co.uk/shop/sim-racing/moza-wheels/moza-rs-v2-sterring-wheel/',
    'fsr2-wheel': 'https://www.abruzzi-official.co.uk/shop/sim-racing/moza-wheels/moza-fsr2-wheel/',
    'srp-pedals': 'https://www.abruzzi-official.co.uk/shop/sim-racing/moza-pedals/srp2-load-cell-pedals/',
    'crp2-pedals': 'https://www.abruzzi-official.co.uk/shop/sim-racing/moza-pedals/moza-crp2-pedals/',
    'hgp-shifter': 'https://www.abruzzi-official.co.uk/shop/sim-racing/sim-racing-accessories/moza-hgp-h-pattern-shifter/',
    'handbrake': 'https://www.abruzzi-official.co.uk/shop/sim-racing/sim-racing-accessories/mozahbphandbrake/',
    'table-clamp': 'https://www.abruzzi-official.co.uk/shop/sim-racing/sim-racing-accessories/moza-r9-r12-r16-r21-table-mounting-bracket/',
  },
  gtomega: {
    'r3-bundle': 'https://www.gtomega.co.uk/products/moza-racing-r3-bundle',
    'r5-bundle': 'https://www.gtomega.co.uk/products/moza-r5-bundle-kit',
    'r9-v3-base': 'https://www.gtomega.co.uk/products/moza-r9-wheel-base',
    'r12-base': 'https://www.gtomega.co.uk/products/moza-racing-r12-wheel-base',
    'r21-base': 'https://www.gtomega.co.uk/products/moza-r21-ultra',
    'esx-wheel': 'https://www.gtomega.co.uk/products/moza-racing-esx-steering-wheel-for-pc-xbox',
    'ks-wheel': 'https://www.gtomega.co.uk/products/moza-racing-ks-steering-wheel',
    'ks-pro-wheel': 'https://www.gtomega.co.uk/products/moza-ks-pro-wheel',
    'cs-wheel': 'https://www.gtomega.co.uk/products/moza-cs-wheel-v2p',
    'cs-pro-wheel': 'https://www.gtomega.co.uk/products/moza-cs-pro-wheel',
    'gs-v2p-wheel': 'https://www.gtomega.co.uk/products/moza-racing-gs-v2p-gt-wheel',
    'rs-wheel': 'https://www.gtomega.co.uk/products/moza-racing-rs-wheel',
    'fsr2-wheel': 'https://www.gtomega.co.uk/products/moza-fsr2-wheel',
    'srp-pedals': 'https://www.gtomega.co.uk/products/moza-srp-two-pedals',
    'crp2-pedals': 'https://www.gtomega.co.uk/products/moza-racing-crp2-pedals',
    'hgp-shifter': 'https://www.gtomega.co.uk/products/moza-racing-hgp-shifter',
    'handbrake': 'https://www.gtomega.co.uk/products/moza-racing-hbp-handbrake',
    'table-clamp': 'https://www.gtomega.co.uk/products/r9-table-clamp',
  },
  apexsim: {
    'r9-v3-base': 'https://www.apexsimracing.com/products/moza-racing-r9-v3-wheel-base-9nm',
    'r12-base': 'https://www.apexsimracing.com/products/moza-racing-r12-wheel-base-12nm',
    'r21-base': 'https://www.apexsimracing.com/collections/sim-racing-direct-drive-wheel-bases/products/moza-racing-r21-ultra-wheelbase-21nm',
    'cs-pro-wheel': 'https://www.apexsimracing.com/products/moza-cs-pro-steering-wheel',
    'ks-pro-wheel': 'https://www.apexsimracing.com/collections/moza-racing-steering-wheels/products/moza-ks-pro-steering-wheel',
    'crp2-pedals': 'https://www.apexsimracing.com/products/moza-racing-crp2-load-cell-pedals',
    'fsr2-wheel': 'https://www.apexsimracing.com/products/moza-racing-fsr2-formula-wheel',
    'esx-wheel': 'https://www.apexsimracing.com/products/moza-racing-esx-steering-wheel',
    'rs-wheel': 'https://www.apexsimracing.com/products/moza-racing-rs-v2-steering-wheel',
  },
  kfire: {
    'r9-v3-base': 'https://www.kfireracing.com.br/base-moza-r9-v2/p',
    'r12-base': 'https://www.kfireracing.com.br/base-moza-r12/p',
    'r21-base': 'https://www.kfireracing.com.br/base-moza-r21-671a8afb04544/p',
    'ks-wheel': 'https://www.kfireracing.com.br/volante-moza-ks/p',
    'gs-v2p-wheel': 'https://www.kfireracing.com.br/volante-moza-gs-v2/p',
    'fsr2-wheel': 'https://www.kfireracing.com.br/volante-moza-fsr2-formula/p',
    'srp-pedals': 'https://www.kfireracing.com.br/pedal-srp/p',
    'crp2-pedals': 'https://www.kfireracing.com.br/pedal-moza-crp2/p',
    'handbrake': 'https://www.kfireracing.com.br/freio-de-mao-moza-hbp/p',
  },
  pagnian: {
    'r3-bundle': 'https://pagnianimports.com.au/products/moza-r3-bundle-for-pc',
    'r5-bundle': 'https://pagnianimports.com.au/products/moza-steering-wheel-r5',
    'r9-v3-base': 'https://pagnianimports.com.au/products/moza-r9-v3-direct-drive-wheel-base',
    'r12-base': 'https://pagnianimports.com.au/products/moza-r12-v2-direct-drive-wheelbase',
    'r16-base': 'https://pagnianimports.com.au/products/moza-r16-v2-direct-drive-wheel-base',
    'r21-base': 'https://pagnianimports.com.au/products/moza-r21-v2-direct-drive-wheel-base',
    'esx-wheel': 'https://pagnianimports.com.au/products/moza-esx',
    'ks-wheel': 'https://pagnianimports.com.au/products/moza-ks-steering-wheel',
    'ks-pro-wheel': 'https://pagnianimports.com.au/products/moza-ks-pro-steering-wheel',
    'cs-wheel': 'https://pagnianimports.com.au/products/moza-cs-v2p-steering-wheel',
    'cs-pro-wheel': 'https://pagnianimports.com.au/products/moza-cs-pro-steering-wheel',
    'gs-v2p-wheel': 'https://pagnianimports.com.au/products/moza-gs-v2p-steering-wheel-microfiber-leather-version',
    'rs-wheel': 'https://pagnianimports.com.au/products/moza-rs-racing-wheel-round-leather',
    'fsr2-wheel': 'https://pagnianimports.com.au/products/moza-fsr2-formula-wheel',
    'srp-pedals': 'https://pagnianimports.com.au/products/moza-srp-pedal',
    'crp2-pedals': 'https://pagnianimports.com.au/products/moza-crp2-pedals-throttle-brake',
    'hgp-shifter': 'https://pagnianimports.com.au/products/moza-hgp-shifter',
    'handbrake': 'https://pagnianimports.com.au/products/moza-hbp-handbrake',
    'table-clamp': 'https://pagnianimports.com.au/products/moza-table-clamp-for-r9-wheel-base',
  },
  'vr-hub': {
    'r3-bundle': 'https://www.virtualracinghub.com/products/moza-r3-bundle',
    'r5-bundle': 'https://www.virtualracinghub.com/products/moza-r5-bundle-in-india',
    'r9-v3-base': 'https://www.virtualracinghub.com/products/moza-racing-r9-v3',
    'r12-base': 'https://www.virtualracinghub.com/products/moza-racing-r12v2',
    'r16-base': 'https://www.virtualracinghub.com/products/moza-r16-v2-direct-drive-wheel-base',
    'r21-base': 'https://www.virtualracinghub.com/products/moza-r21-ultra',
    'esx-wheel': 'https://www.virtualracinghub.com/products/es-steering-wheel-india',
    'ks-wheel': 'https://www.virtualracinghub.com/products/moza-racing-ks-wheel-india',
    'ks-pro-wheel': 'https://www.virtualracinghub.com/products/moza-ks-pro-steering-wheel',
    'cs-wheel': 'https://www.virtualracinghub.com/products/moza-racing-cs-steering-wheel',
    'cs-pro-wheel': 'https://www.virtualracinghub.com/products/moza-cs-pro-steering-wheel',
    'gs-v2p-wheel': 'https://www.virtualracinghub.com/products/moza-racing-gs-wheel-india',
    'rs-wheel': 'https://www.virtualracinghub.com/products/rs-v2-steering-wheel-india',
    'fsr2-wheel': 'https://www.virtualracinghub.com/products/moza-fsr2-formula-wheel',
    'crp2-pedals': 'https://www.virtualracinghub.com/products/moza-crp2-pedals',
    'hgp-shifter': 'https://www.virtualracinghub.com/products/moza-hgp-shifter-india',
    'handbrake': 'https://www.virtualracinghub.com/products/moza-hbp-handbrake-india',
    'table-clamp': 'https://www.virtualracinghub.com/products/moza-table-fixed-clamp-india',
  },
  simufy: {
    'r3-bundle':    'https://simufy.com/en/products/pack-dd-r3-moza-solo-pc',
    'r5-bundle':    'https://simufy.com/en/products/pack-dd-r5-moza',
    'r9-bundle':    'https://simufy.com/en/products/copia-de-pack-dd-r9-moza',
    'r9-v3-base':   'https://simufy.com/en/products/base-direct-drive-r9-v3-moza',
    'r12-base':     'https://simufy.com/en/products/base-direct-drive-r12-v2-moza',
    'r21-base':     'https://simufy.com/en/products/base-direct-drive-r21-ultra',
    'esx-wheel':    'https://simufy.com/en/products/volante-es-moza',
    'ks-wheel':     'https://simufy.com/en/products/volante-ks-moza',
    'ks-pro-wheel': 'https://simufy.com/en/products/volante-moza-ks-pro',
    'cs-pro-wheel': 'https://simufy.com/en/products/volante-cs-pro-moza',
    'gs-v2p-wheel': 'https://simufy.com/en/products/volante-gs-v2p-moza',
    'rs-wheel':     'https://simufy.com/en/products/volante-moza-rs-v2',
    'fsr2-wheel':   'https://simufy.com/en/products/volante-fsr2-moza',
    'vision-gs':    'https://simufy.com/en/products/volante-vgs-moza',
    'srp-pedals':   'https://simufy.com/en/products/pedales-moza-srp2',
    'crp2-pedals':  'https://simufy.com/en/products/pedales-crp2-moza',
    'hgp-shifter':  'https://simufy.com/en/products/shifter-hgp-h-moza',
    'handbrake':    'https://simufy.com/en/products/freno-de-mano-hbp-moza',
    'table-clamp':  'https://simufy.com/en/products/moza-r9-table-clamp',
    'ab9-base':     'https://simufy.com/en/products/base-moza-ab9',
  },
  'son-video': {
    'r5-bundle':    'https://www.son-video.com/article/370-volants-gaming/moza-racing/moza-racing-r5-bundle-base-plus-volant-pedales',
    'r9-v3-base':   'https://www.son-video.com/article/348-accessoires-gaming/moza-racing/r9-v3-rs080',
    'r12-base':     'https://www.son-video.com/article/348-accessoires-gaming/moza-racing/r12-v2-rs081',
    'r16-base':     'https://www.son-video.com/article/348-accessoires-gaming/moza-racing/r16',
    'r21-base':     'https://www.son-video.com/article/348-accessoires-gaming/moza-racing/r21',
    'esx-wheel':    'https://www.son-video.com/article/370-volants-gaming/moza-racing/esx-rs052',
    'ks-wheel':     'https://www.son-video.com/article/370-volants-gaming/moza-racing/ks',
    'ks-pro-wheel': 'https://www.son-video.com/article/370-volants-gaming/moza-racing/ks-pro-rs095',
    'cs-wheel':     'https://www.son-video.com/article/370-volants-gaming/moza-racing/cs-v2p-rs057',
    'cs-pro-wheel': 'https://www.son-video.com/article/370-volants-gaming/moza-racing/cs-pro-rs093',
    'gs-v2p-wheel': 'https://www.son-video.com/article/370-volants-gaming/moza-racing/gs-v2p-gt',
    'rs-wheel':     'https://www.son-video.com/article/370-volants-gaming/moza-racing/volant-cuir-rs',
    'fsr2-wheel':   'https://www.son-video.com/article/370-volants-gaming/moza-racing/fsr2-rs068',
    'vision-gs':    'https://www.son-video.com/article/370-volants-gaming/moza-racing/vision-gs',
    'srp-pedals':   'https://www.son-video.com/article/369-pedaliers-gaming/moza-racing/sr-p',
    'crp2-pedals':  'https://www.son-video.com/article/369-pedaliers-gaming/moza-racing/crp2',
    'hgp-shifter':  'https://www.son-video.com/article/348-accessoires-gaming/moza-racing/hgp',
    'handbrake':    'https://www.son-video.com/article/348-accessoires-gaming/moza-racing/hbp',
    'table-clamp':  'https://www.son-video.com/article/348-accessoires-gaming/moza-racing/r9',
    'ab6-bundle':   'https://www.son-video.com/article/348-accessoires-gaming/moza-racing/ab6-flight-simulator-bundle',
    'ab9-base':     'https://www.son-video.com/article/348-accessoires-gaming/moza-racing/ab9-ffb-base',
    'mh16-stick':   'https://www.son-video.com/article/348-accessoires-gaming/moza-racing/mh16-flightstick-as002',
    'ma3x-stick':   'https://www.son-video.com/article/348-accessoires-gaming/moza-racing/ma3x-side-stick-as005',
    'mtq-throttle': 'https://www.son-video.com/article/348-accessoires-gaming/moza-racing/mtq-as014',
    'mtp-throttle': 'https://www.son-video.com/article/348-accessoires-gaming/moza-racing/mtp-throttle-panel-as008',
    'mtlp-panel':   'https://www.son-video.com/article/348-accessoires-gaming/moza-racing/mtlp-take-off-landing-panel-as009',
    'mrp-pedals':   'https://www.son-video.com/article/369-pedaliers-gaming/moza-racing/mrp-rudder-pedals-as019',
  },
  caseking: {
    'r3-bundle':    'https://www.caseking.de/en/moza-r3-racing-set-xbox-pc/GAJO-545.html',
    'r5-bundle':    'https://www.caseking.de/en/moza-r5-racing-set-r5-dd-wheelbase-es-wheel-sr-p-lite-pedals-table-mount/GAJO-379.html',
    'r3-base':      'https://www.caseking.de/en/moza-r3-racing-wheel-and-pedals-for-pc/GAJO-904.html',
    'r9-v3-base':   'https://www.caseking.de/en/moza-r9-v3-direct-drive-wheelbase-9-nm/GAJO-1007.html',
    'r12-base':     'https://www.caseking.de/en/moza-r12-v2-direct-drive-wheelbase-12-nm/GAJO-1008.html',
    'ks-wheel':     'https://www.caseking.de/en/moza-ks-gt-steering-wheel-30-cm/GAJO-536.html',
    'cs-wheel':     'https://www.caseking.de/en/moza-cs-v2p-lenkrad/GAJO-652.html',
    'gs-v2p-wheel': 'https://www.caseking.de/en/moza-gs-v2p-steering-wheel/GAJO-568.html',
    'rs-wheel':     'https://www.caseking.de/en/moza-rs-v2-steering-wheel-round-leather-33-cm/GAJO-410.html',
    'fsr2-wheel':   'https://www.caseking.de/en/moza-fsr2-high-end-formula-steering-wheel-28-cm/GAJO-905.html',
    'vision-gs':    'https://www.caseking.de/en/moza-vision-gs-simracing-steering-wheel/GAJO-849.html',
    'srp-pedals':   'https://www.caseking.de/en/moza-sr-p-load-cell-pedals/GAJO-384.html',
    'hgp-shifter':  'https://www.caseking.de/en/moza-hgp-h-shifter/GAJO-463.html',
    'handbrake':    'https://www.caseking.de/en/moza-hbp-handbrake/GAJO-453.html',
    'table-clamp':  'https://www.caseking.de/en/moza-table-clamp-for-r5-r9-and-r12/GAJO-394.html',
    'ab6-bundle':   'https://www.caseking.de/en/moza-ab6-flight-simulator-bundle-6nm-force-feedback-argb-black/GAJO-1229.html',
    'mh16-stick':   'https://www.caseking.de/en/moza-mh16-flightstick/GAJO-856.html',
    'ma3x-stick':   'https://www.caseking.de/en/moza-ma3x-sidestick-black/GAJO-935.html',
    'mtp-throttle': 'https://www.caseking.de/en/moza-mtp-throttle-panel/GAJO-990.html',
    'mtlp-panel':   'https://www.caseking.de/en/moza-mtlp-take-off-landing-panel/GAJO-991.html',
    'mrp-pedals':   'https://www.caseking.de/en/moza-mrp-rudder-pedals/GAJO-1307.html',
  },
  gomotorsports: {
    'r3-bundle':    'https://gomotorsportsshop.com/products/moza-r3-pc-xbox-bundle',
    'r5-bundle':    'https://gomotorsportsshop.com/products/moza-r5-bundle',
    'r9-bundle':    'https://gomotorsportsshop.com/products/moza-r9-v3-wheel-base-packages',
    'r9-v3-base':   'https://gomotorsportsshop.com/products/moza-r9-v2-wheel-base',
    'r12-base':     'https://gomotorsportsshop.com/products/moza-r12-wheel-base-v2',
    'r21-base':     'https://gomotorsportsshop.com/products/moza-r21-ultra-direct-drive-wheel-base',
    'esx-wheel':    'https://gomotorsportsshop.com/products/moza-esx-steering-wheel',
    'ks-wheel':     'https://gomotorsportsshop.com/products/moza-ks-steering-wheel',
    'cs-wheel':     'https://gomotorsportsshop.com/products/moza-cs-v2p-steering-wheel',
    'cs-pro-wheel': 'https://gomotorsportsshop.com/products/moza-cs-pro-steering-wheel',
    'gs-v2p-wheel': 'https://gomotorsportsshop.com/products/moza-gs-v2p-gt-wheel',
    'fsr2-wheel':   'https://gomotorsportsshop.com/products/moza-fsr-formula-wheel',
    'vision-gs':    'https://gomotorsportsshop.com/products/moza-vision-gs-wheel',
    'srp-pedals':   'https://gomotorsportsshop.com/products/moza-sr-p-pedal',
    'crp2-pedals':  'https://gomotorsportsshop.com/products/moza-crp2-load-cell-pedals',
    'hgp-shifter':  'https://gomotorsportsshop.com/products/moza-hgp-shifter',
    'handbrake':    'https://gomotorsportsshop.com/products/moza-hbp-handbrake',
    'table-clamp':  'https://gomotorsportsshop.com/products/moza-table-mounting-bracket',
  },
  simracingpros: {
    'r5-bundle':    'https://www.simracingpros.com/products/moza-r5-bundle',
    'r12-base':     'https://www.simracingpros.com/products/moza-r12-base-pre-order',
    'esx-wheel':    'https://www.simracingpros.com/products/esx-steering-wheel-for-pc-xbox',
    'ks-wheel':     'https://www.simracingpros.com/products/moza-ks-wheel-pre-order-estimated-arrival-early-august',
    'vision-gs':    'https://www.simracingpros.com/products/moza-vision-gs-wheel-pre-order',
    'srp-pedals':   'https://www.simracingpros.com/products/moza-sr-p-pedal-no-clutch',
    'crp2-pedals':  'https://www.simracingpros.com/products/moza-crp2-load-cell-pedals',
    'hgp-shifter':  'https://www.simracingpros.com/products/moza-hgp-shifter-pre-order',
    'handbrake':    'https://www.simracingpros.com/products/moza-hbp-handbrake-pre-order',
    'table-clamp':  'https://www.simracingpros.com/products/moza-r9-table-clamp',
    'ab9-base':     'https://www.simracingpros.com/products/moza-ab9-ffb-base',
  },
  racegear: {
    'r5-bundle':    'https://www.racegear.eu/en/wheelbases/83-moza-r5-bundle-for-pc-rs20-0723497239493.html',
    'r9-v3-base':   'https://www.racegear.eu/en/wheelbases/150-moza-r9-v3-direct-drive-wheelbase-rs080-6973137270810.html',
    'ks-wheel':     'https://www.racegear.eu/en/steering-wheels/123-moza-ks-steering-wheel-for-pc-rs047-0723497239752.html',
    'cs-wheel':     'https://www.racegear.eu/en/steering-wheels/153-moza-cs-v2p-steering-wheel-rs057-0723497239905.html',
    'fsr2-wheel':   'https://www.racegear.eu/en/steering-wheels/200-moza-fsr2-280mm-formula-wheel-with-touchscreen-rs068-demo-6973137270599.html',
    'srp-pedals':   'https://www.racegear.eu/en/sim-racing-pedals/122-moza-sr-p-lite-clutch-pedal-rs19-0723497239486.html',
    'table-clamp':  'https://www.racegear.eu/en/accessories-for-steering-wheels/86-moza-r5r9-table-clamp-rs12-0723497239325.html',
  },
  electronicscrazy: {
    'srp-pedals':   'https://www.electronicscrazy.sg/moza-racing-rs111-sr-p-2-pedals-load-cell-sim-racing-pedal-set-with-adjustable-design/',
    'crp2-pedals':  'https://www.electronicscrazy.sg/moza-racing-crp2-pedal-set-rs066-3-pedal-system-for-sim-racing-pc/',
    'mtlp-panel':   'https://www.electronicscrazy.sg/moza-racing-as009-mtlp-panel-pro-sim-racing-multi-function-control-module/',
  },
  // demontweeks: blocked by anti-bot (HTTP 403), kept in Instagram monitoring only
  advancedsimracing: {
    'r5-bundle':    'https://www.advancedsimracing.com/products/moza-r5-racing-simulator-bundle',
    'r9-v3-base':   'https://www.advancedsimracing.com/products/moza-r9-direct-drive-wheel-base',
    'r12-base':     'https://www.advancedsimracing.com/products/moza-racing-r12-direct-drive-wheel-base',
    'r16-base':     'https://www.advancedsimracing.com/products/moza-r16-direct-drive-wheel-base',
    'r21-base':     'https://www.advancedsimracing.com/products/moza-racing-r21-ultra-wheel-base',
    'ks-wheel':     'https://www.advancedsimracing.com/products/moza-racing-ks-steering-wheel',
    'ks-pro-wheel': 'https://www.advancedsimracing.com/products/moza-racing-ks-pro-steering-wheel',
    'cs-wheel':     'https://www.advancedsimracing.com/products/moza-racing-cs-steering-wheel',
    'gs-v2p-wheel': 'https://www.advancedsimracing.com/products/moza-gs-gt-wheel',
    'rs-wheel':     'https://www.advancedsimracing.com/products/moza-rs-wheel',
    'fsr2-wheel':   'https://www.advancedsimracing.com/products/moza-racing-fsr2-formula-wheel',
    'vision-gs':    'https://www.advancedsimracing.com/products/moza-racing-vision-gs-steering-wheel',
    'esx-wheel':    'https://www.advancedsimracing.com/products/moza-racing-esx-wheel-for-xbox',
    'srp-pedals':   'https://www.advancedsimracing.com/products/moza-racing-srp-pedals',
    'crp2-pedals':  'https://www.advancedsimracing.com/products/moza-racing-crp-2-pedals',
    'hgp-shifter':  'https://www.advancedsimracing.com/products/moza-hgp-shifter',
    'handbrake':    'https://www.advancedsimracing.com/products/moza-racing-hbp-handbrake',
    'table-clamp':  'https://www.advancedsimracing.com/products/moza-racing-r5-r9-table-clamp',
  },
  maxgaming: {
    'r5-bundle':    'https://www.maxgaming.se/sv/pc-rattar/r5-racing-simulator-r5-wheel-base-es-steering-wheel-sr-p-lite-pedals-bundle',
    'r9-v3-base':   'https://www.maxgaming.se/sv/pc-rattar/r9-v3-direct-drive-wheelbase-svart-servomotor-rattbas',
    'r12-base':     'https://www.maxgaming.se/sv/pc-rattar/r12-v2-direct-drive-wheelbase-svart-servomotor-rattbas',
    'ks-wheel':     'https://www.maxgaming.se/sv/pc-rattar/ks-steering-wheel-300mm-butterfly-style-gt-wheel-ratt-for-racing',
    'ks-pro-wheel': 'https://www.maxgaming.se/sv/pc-rattar/moza-racing-ks-pro-racing-ratt',
    'cs-wheel':     'https://www.maxgaming.se/sv/pc-rattar/cs-v2p-leather-steering-wheel-33cm-ratt-for-racing',
    'rs-wheel':     'https://www.maxgaming.se/sv/pc-rattar/rs-v2-steering-wheel-round-leather-33cm-ratt-for-racing',
    'fsr2-wheel':   'https://www.maxgaming.se/sv/pc-rattar/moza-fsr2-formula-wheel',
    'vision-gs':    'https://www.maxgaming.se/sv/pc-rattar/moza-racing-vision-gs-wheel',
    'esx-wheel':    'https://www.maxgaming.se/sv/xbox-x-ratt/moza-racing-esx-steering-wheel',
    'srp-pedals':   'https://www.maxgaming.se/sv/pc-rattar/sr-p-two-pedals-throttle-and-brake-pedalsett-gas-broms',
    'crp2-pedals':  'https://www.maxgaming.se/sv/pc-rattar/moza-crp2-load-cell-pedals',
    'hgp-shifter':  'https://www.maxgaming.se/sv/pc-rattar/hgp-h-shifter-vaxelspak',
    'handbrake':    'https://www.maxgaming.se/sv/pc-rattar/hbp-handbroms-pc-rattbas',
    'table-clamp':  'https://www.maxgaming.se/sv/pc-rattar/table-clamp-bordsklamma-till-rattbas-r9-r5',
  },
  simline: {
    'r5-bundle':    'https://simline.eu/en/simracing-bundles/moza-r5-bundle',
    'r9-v3-base':   'https://simline.eu/en/moza-direct-drive-bases/moza-r9-v3',
    'r12-base':     'https://simline.eu/en/moza-direct-drive-bases/moza-r12-v2',
    'r21-base':     'https://simline.eu/en/moza-direct-drive-bases/moza-r21',
    'ks-wheel':     'https://simline.eu/en/moza-wheels/moza-ks',
    'ks-pro-wheel': 'https://simline.eu/en/moza-wheels/moza-ks-pro',
    'cs-wheel':     'https://simline.eu/en/moza-wheels/moza-cs-v2p',
    'cs-pro-wheel': 'https://simline.eu/en/moza-wheels/moza-cs-pro',
    'gs-v2p-wheel': 'https://simline.eu/en/moza-wheels/moza-gs-v2p',
    'rs-wheel':     'https://simline.eu/en/moza-wheels/moza-rs-v2',
    'fsr2-wheel':   'https://simline.eu/en/moza-wheels/moza-fsr2',
    'vision-gs':    'https://simline.eu/en/moza-wheels/moza-vision-gs',
    'esx-wheel':    'https://simline.eu/en/moza-wheels/moza-esx',
    'srp-pedals':   'https://simline.eu/en/moza-pedals/moza-srp2',
    'crp2-pedals':  'https://simline.eu/en/moza-pedals/moza-crp2',
    'hgp-shifter':  'https://simline.eu/en/moza-handbrakes-shifters/moza-hgp-h-shifter',
    'handbrake':    'https://simline.eu/en/simracing-shifters/moza-hbp-handbrake',
    'table-clamp':  'https://simline.eu/en/accessories/moza-table-clamp',
  },
  simracewebshop: {
    'r5-bundle':    'https://www.simracewebshop.com/products/moza-racing-r5-direct-drive-simulator-bundle',
    'r9-v3-base':   'https://www.simracewebshop.com/products/moza-racing-r9-direct-drive-wheel-base-v3',
    'r12-base':     'https://www.simracewebshop.com/products/moza-racing-r12-direct-drive-wheel-base-v2',
    'ks-wheel':     'https://www.simracewebshop.com/products/moza-racing-ks-steering-wheel',
    'srp-pedals':   'https://www.simracewebshop.com/products/moza-racing-sr-p-pedals',
  },
  gamergeardirect: {
    'r5-bundle':    'https://www.gamergeardirect.com.au/products/moza-racing-r5-bundle',
    'r9-v3-base':   'https://www.gamergeardirect.com.au/products/moza-r9-v3-wheelbase',
    'r12-base':     'https://www.gamergeardirect.com.au/products/moza-r12-v2-wheelbase',
    'ks-wheel':     'https://www.gamergeardirect.com.au/products/moza-ks-formula-racing-wheel',
    'srp-pedals':   'https://www.gamergeardirect.com.au/products/moza-sr-p-pedals',
    'crp2-pedals':  'https://www.gamergeardirect.com.au/products/moza-crp2-load-cell-pedals',
    'hgp-shifter':  'https://www.gamergeardirect.com.au/products/moza-hgp-shifter',
    'handbrake':    'https://www.gamergeardirect.com.au/products/moza-hbp-handbrake',
    'table-clamp':  'https://www.gamergeardirect.com.au/products/moza-table-clamp',
  },
  player1simgear: {
    'r3-bundle':    'https://p1simgear.com.au/products/moza-r3-direct-drive-racing-bundle-pc',
    'r9-v3-base':   'https://p1simgear.com.au/products/moza-racing-r9-v3-direct-drive-wheel-base',
    'r12-base':     'https://p1simgear.com.au/products/moza-r12-v2-wheel-base',
    'r21-base':     'https://p1simgear.com.au/products/moza-r21-ultra-true-torque-direct-drive-wheel-base',
    'ks-wheel':     'https://p1simgear.com.au/products/moza-ks-steering-wheel',
    'ks-pro-wheel': 'https://p1simgear.com.au/products/moza-ks-pro-steering-wheel',
    'cs-wheel':     'https://p1simgear.com.au/products/moza-cs-steering-wheel',
    'cs-pro-wheel': 'https://p1simgear.com.au/products/moza-cs-pro-steering-wheel',
    'fsr2-wheel':   'https://p1simgear.com.au/products/moza-fsr-v2-formula-wheel',
    'srp-pedals':   'https://p1simgear.com.au/products/moza-srp-pedals',
    'crp2-pedals':  'https://p1simgear.com.au/products/moza-crp2-pedals',
    'hgp-shifter':  'https://p1simgear.com.au/products/moza-hgp-shifter',
    'handbrake':    'https://p1simgear.com.au/products/moza-hbp-handbrake',
  },
  jbhifi: {
    'r5-bundle':    'https://www.jbhifi.com.au/products/moza-r5-racing-bundle-for-pc',
    'r9-v3-base':   'https://www.jbhifi.com.au/products/moza-r9-v3-direct-drive-wheel-base',
    'r12-base':     'https://www.jbhifi.com.au/products/moza-r12-v2-direct-drive-wheel-base',
    'r21-base':     'https://www.jbhifi.com.au/products/moza-r21-ultra-direct-drive-wheel-base',
    'ks-wheel':     'https://www.jbhifi.com.au/products/moza-ks-steering-wheel',
    'ks-pro-wheel': 'https://www.jbhifi.com.au/products/moza-ks-pro-steering-wheel',
    'cs-pro-wheel': 'https://www.jbhifi.com.au/products/moza-cs-pro-steering-wheel',
    'hgp-shifter':  'https://www.jbhifi.com.au/products/moza-hgp-shifter',
    'handbrake':    'https://www.jbhifi.com.au/products/moza-hbp-handbrake',
  },
  // thegamesmen: blocked by anti-bot (HTTP 403), kept in Instagram monitoring only
  alternate: {
    'r5-bundle':    'https://www.alternate.de/MOZA/R5-Bundle-Lenkrad/html/product/1912680',
    'r9-v3-base':   'https://www.alternate.de/MOZA/R9-V3-Wheel-Base-Lenkradbasis/html/product/100121863',
    'r12-base':     'https://www.alternate.de/MOZA/R12-V2-Wheel-Base-Lenkradbasis/html/product/100121864',
    'r21-base':     'https://www.alternate.de/MOZA/R21-Ultra-DD-Lenkradbasis/html/product/100167208',
    'ks-wheel':     'https://www.alternate.de/MOZA/KS-Steering-Wheel-Austausch-Lenkrad/html/product/100003165',
    'ks-pro-wheel': 'https://www.alternate.de/MOZA/KS-Pro-Steering-Wheel-Austausch-Lenkrad/html/product/100177838',
    'cs-wheel':     'https://www.alternate.de/MOZA/CS-V2P-Steering-Wheel-Austausch-Lenkrad/html/product/100032059',
    'cs-pro-wheel': 'https://www.alternate.de/MOZA/CS-Pro-Steering-Wheel-Austausch-Lenkrad/html/product/100177828',
    'gs-v2p-wheel': 'https://www.alternate.de/MOZA/GS-V2P-GT-Wheel-Microfiber-Leather-Austausch-Lenkrad/html/product/100032058',
    'esx-wheel':    'https://www.alternate.de/MOZA/ESX-Steering-Wheel-fuer-Xbox-Austausch-Lenkrad/html/product/100032057',
    'rs-wheel':     'https://www.alternate.de/MOZA/RS-V2-Steering-Wheel-Austausch-Lenkrad/html/product/1912674',
    'fsr2-wheel':   'https://www.alternate.de/MOZA/FSR2-Formula-Wheel-Austausch-Lenkrad/html/product/100077819',
    'srp-pedals':   'https://www.alternate.de/MOZA/SR-P-Pedal-Set-of-2-Pedale/html/product/1912677',
    'crp2-pedals':  'https://www.alternate.de/MOZA/CRP2-Load-Cell-Gaspedal-plus-Bremse-Pedale/html/product/100077820',
    'hgp-shifter':  'https://www.alternate.de/MOZA/HGP-Shifter-Schalthebel/html/product/1912700',
    'handbrake':    'https://www.alternate.de/MOZA/HBP-Handbrake-Handbremse/html/product/1912696',
    'table-clamp':  'https://www.alternate.de/MOZA/Table-Clamp-Halterung/html/product/1912694',
  },
  // MOZA Flight (飞模) product URLs
  gtomega: {
    'ab9-base':     'https://www.gtomega.co.uk/products/moza-flight-ab9-base',
    'mh16-stick':   'https://www.gtomega.co.uk/products/moza-flight-mh16-flightstick',
    'mtp-throttle': 'https://www.gtomega.co.uk/products/moza-flight-mtp-throttle-panel',
    'mtq-throttle': 'https://www.gtomega.co.uk/products/moza-mtq-throttle-panel',
    'mtlp-panel':   'https://www.gtomega.co.uk/products/moza-flight-mtp-take-off-panel',
  },
  pagnian: {
    'ab6-bundle':   'https://pagnianimports.com.au/products/moza-ab6-flight-simulator',
    'mh16-stick':   'https://pagnianimports.com.au/products/moza-mh16-flightstick',
  },
  'simmotion-us': {
    'ab9-base':     'https://us.sim-motion.com/products/moza-flight-ab9-base',
  },
  // Batch 2: Shopify stores
  speednation: {
    'r5-bundle':    'https://speednation.co.nz/products/moza-racing-r5',
    'r9-v3-base':   'https://speednation.co.nz/products/moza-r9-v3-direct-drive-wheel-base',
    'ks-wheel':     'https://speednation.co.nz/products/moza-racing-ks-steering-wheel',
    'srp-pedals':   'https://speednation.co.nz/products/moza-racing-srp-2-pedals-set',
    'srp-lite':     'https://speednation.co.nz/products/moza-sr-p-lite-clutch-pedal',
    'table-clamp':  'https://speednation.co.nz/products/moza-racing-r9-table-clamp',
  },
  simhubpro: {
    'r3-bundle':    'https://simhub.pro/products/moza-r3-bundle-for-pc',
    'r5-bundle':    'https://simhub.pro/products/moza-r5-bundle',
    'r9-v3-base':   'https://simhub.pro/products/moza-r9-v3-direct-drive-wheelbase',
    'r12-base':     'https://simhub.pro/products/moza-r12-v2-direct-drive-wheelbase',
    'ks-wheel':     'https://simhub.pro/products/moza-ks',
    'cs-wheel':     'https://simhub.pro/products/moza-cs-v2p-dual-clutch',
    'gs-v2p-wheel': 'https://simhub.pro/products/moza-gs-v2p-microfiber-leather',
    'rs-wheel':     'https://simhub.pro/products/moza-rs-v2-leather',
    'fsr2-wheel':   'https://simhub.pro/products/moza-fsr2-formula-wheel',
    'vision-gs':    'https://simhub.pro/products/moza-vision-gs',
    'esx-wheel':    'https://simhub.pro/products/moza-esx-for-xbox',
    'srp-pedals':   'https://simhub.pro/products/moza-sr-p-dual',
    'crp2-pedals':  'https://simhub.pro/products/moza-crp2',
    'hgp-shifter':  'https://simhub.pro/products/moza-hgp-shifter',
    'handbrake':    'https://simhub.pro/products/moza-hbp-handbrake',
    'ab9-base':     'https://simhub.pro/products/moza-ab9',
    'mh16-stick':   'https://simhub.pro/products/moza-mh16-flightstick',
    'ma3x-stick':   'https://simhub.pro/products/moza-ma3x-sidestick',
    'mtp-throttle': 'https://simhub.pro/products/moza-mtp-throttle-panel',
  },
  // delenordic.com redirects to apex300.com (Shopify CDN)
  delenordic: {
    'gs-v2p-wheel': 'https://apex300.com/products/moza-gs-v2p-formula-wheel',
    'vision-gs':    'https://apex300.com/products/moza-racing-vision-gs-wheel',
    'hgp-shifter':  'https://apex300.com/products/moza-hgp-shifter',
    'crp2-pedals':  'https://apex300.com/products/moza-crp-load-cell-three-pedals-with-base',
  },
  simulatorcave: {
    'r3-bundle':    'https://simulatorcave.com/product/moza-r3-racing-wheel-and-pedals-for-xbox/',
    'r5-bundle':    'https://simulatorcave.com/product/moza-r5-bundle/',
  },
  sdeal: {
    'r3-bundle':    'https://www.sdeal.com.my/moza-racing/2026-moza-racing-r3-direct-drive-dd-complete-set-2-3-pedals-with-steering-wheel',
    'r5-bundle':    'https://www.sdeal.com.my/moza-racing/moza-racing-r5-direct-drive-dd-complete-set-2-3-pedals-with-steering-wheel',
    'r9-v3-base':   'https://www.sdeal.com.my/moza-racing/moza-r9-direct-drive-base',
    'r12-base':     'https://www.sdeal.com.my/moza-racing/moza-racing-r12-direct-drive-12nm-base-only',
    'r16-base':     'https://www.sdeal.com.my/moza-racing/moza-r16-direct-base',
    'ks-wheel':     'https://www.sdeal.com.my/moza-racing/new-pre-order-moza-racing-ks-gt-racing-wheel',
    'gs-v2p-wheel': 'https://www.sdeal.com.my/moza-racing/moza-racing-gs-gt-wheel-300mm-wheel',
    'rs-wheel':     'https://www.sdeal.com.my/moza-racing/moza-racing-rsv2-13-inch-round-wheel',
    'fsr2-wheel':   'https://www.sdeal.com.my/moza-racing/moza-racing-fsr-formula-steering-wheel',
    'vision-gs':    'https://www.sdeal.com.my/moza-racing/moza-vision-gs-wheel',
    'es-wheel':     'https://www.sdeal.com.my/moza-racing/standalone-es-steering-wheel',
    'hgp-shifter':  'https://www.sdeal.com.my/moza-racing/moza-racing-hgp-cnc-8-speed-shifter',
    'handbrake':    'https://www.sdeal.com.my/moza-racing/moza-hbp-loadcell-handbrake',
    'srp-pedals':   'https://www.sdeal.com.my/moza-racing/moza-srp-pedal-clutch',
    'crp2-pedals':  'https://www.sdeal.com.my/moza-racing/moza-racing-crp-v2-alloy-loadcell-pedals',
  },
  // Batch 3: New dealers (May 2026)
  simracer: {
    'r3-bundle':    'https://simracer.at/products/moza-r3-racing-set-fur-pc',
    'r5-bundle':    'https://simracer.at/products/moza-r5-racing-set-r5-direct-drive-wheelbase-es-lenkrad-sr-p-lite-pedale',
    'r9-v3-base':   'https://simracer.at/products/moza-r9-v3-direct-drive-wheelbase-9-nm',
    'r12-base':     'https://simracer.at/products/moza-r12-v2-direct-drive-wheelbase-12-nm',
    'r21-base':     'https://simracer.at/products/moza-r21-ultra-dd-wheelbase-21nm',
    'esx-wheel':    'https://simracer.at/products/moza-esx-steering-wheel-fur-xbox',
    'ks-wheel':     'https://simracer.at/products/moza-ks-gt-lenkrad',
    'ks-pro-wheel': 'https://simracer.at/products/moza-ks-pro-wheel',
    'cs-wheel':     'https://simracer.at/products/moza-racing-csv2p-racing-wheel',
    'cs-pro-wheel': 'https://simracer.at/products/moza-cs-pro-lenkrad',
    'gs-v2p-wheel': 'https://simracer.at/products/moza-racing-gs-gt-v2p-wheel',
    'rs-wheel':     'https://simracer.at/products/moza-rs-v2-lenkrad-rund-33-cm',
    'fsr2-wheel':   'https://simracer.at/products/moza-fsr2-formel-lenkrad-highend',
    'vision-gs':    'https://simracer.at/products/moza-vision-gs-wheel',
    'srp-pedals':   'https://simracer.at/products/moza-srp2-pedal-set',
    'crp2-pedals':  'https://simracer.at/products/moza-crp2-load-cell-pedals',
    'hgp-shifter':  'https://simracer.at/products/moza-racing-hgp-h-shifter',
    'handbrake':    'https://simracer.at/products/moza-hbp-handbremse',
    'table-clamp':  'https://simracer.at/products/moza-tischklemme-fur-r9',
    'ab9-base':     'https://simracer.at/products/moza-ab9-ffb-base',
    'mh16-stick':   'https://simracer.at/products/moza-mh16-flightstick',
    'ma3x-stick':   'https://simracer.at/products/moza-max3-side-stick',
    'mrp-pedals':   'https://simracer.at/products/moza-mrp-ruder-pedale',
  },
  simultimate: {
    'r3-bundle':    'https://simultimate.ch/produkt/moza-r3-racing-set-39-nm/',
    'r5-bundle':    'https://simultimate.ch/produkt/moza-r5-racing-set-55-nm/',
    'r9-v3-base':   'https://simultimate.ch/produkt/moza-r9-v3-direct-drive-wheel-base-9-nm/',
    'r12-base':     'https://simultimate.ch/produkt/moza-r12-v2-direct-drive-wheel-base-12-nm/',
    'r21-base':     'https://simultimate.ch/produkt/moza-r21-ultra-dd-wheel-base-21-nm/',
    'esx-wheel':    'https://simultimate.ch/produkt/moza-esx-steering-wheel/',
    'ks-wheel':     'https://simultimate.ch/produkt/moza-ks-steering-wheel/',
    'ks-pro-wheel': 'https://simultimate.ch/produkt/moza-ks-pro-steering-wheel/',
    'cs-wheel':     'https://simultimate.ch/produkt/moza-cs-v2p-steering-wheel/',
    'cs-pro-wheel': 'https://simultimate.ch/produkt/moza-cs-pro-steering-wheel/',
    'gs-v2p-wheel': 'https://simultimate.ch/produkt/moza-gs-v2p-gt-wheel/',
    'rs-wheel':     'https://simultimate.ch/produkt/moza-rs-v2-steering-wheel/',
    'fsr2-wheel':   'https://simultimate.ch/produkt/moza-fsr2-formula-wheel/',
    'vision-gs':    'https://simultimate.ch/produkt/moza-vision-gs-wheel/',
    'srp-pedals':   'https://simultimate.ch/produkt/moza-srp2-brake-throttle/',
    'crp2-pedals':  'https://simultimate.ch/produkt/moza-crp2-pedalset/',
    'hgp-shifter':  'https://simultimate.ch/produkt/moza-hgp-h-shifter/',
    'handbrake':    'https://simultimate.ch/produkt/moza-hbp-handbrake/',
    'table-clamp':  'https://simultimate.ch/produkt/moza-table-clamp/',
    'ab9-base':     'https://simultimate.ch/produkt/moza-ab9-base-12-nm/',
    'mh16-stick':   'https://simultimate.ch/produkt/moza-mh16-flight-stick/',
    'ma3x-stick':   'https://simultimate.ch/produkt/moza-ma3x-side-stick/',
    'mrp-pedals':   'https://simultimate.ch/produkt/moza-mrp-rudder-pedals/',
    'mtp-throttle': 'https://simultimate.ch/produkt/moza-mtp-throttle/',
    'mtlp-panel':   'https://simultimate.ch/produkt/moza-mtlp-panel/',
    'mtq-throttle': 'https://simultimate.ch/produkt/moza-mtq-throttle-quadrant/',
  },
  arcteam: {
    'r5-bundle':    'https://moza.arc-team.it/volante-sim-racing-moza-racing-r5',
    'r9-v3-base':   'https://moza.arc-team.it/volante-sim-racing-moza-racing-r9',
    'r16-base':     'https://moza.arc-team.it/moza-racing/r16-base-direct-drive',
    'r21-base':     'https://moza.arc-team.it/moza-racing/r21-moza-base-direct-drive',
    'cs-wheel':     'https://moza.arc-team.it/volante-cs-moza',
    'gs-v2p-wheel': 'https://moza.arc-team.it/volante-moza-gs',
    'rs-wheel':     'https://moza.arc-team.it/volante-rs-moza',
    'fsr2-wheel':   'https://moza.arc-team.it/volante-moza-fsr',
    'srp-pedals':   'https://moza.arc-team.it/pedaliera-sim-racing-moza-sr-p',
    'hgp-shifter':  'https://moza.arc-team.it/cambio-ad-h-moza-hgp',
    'handbrake':    'https://moza.arc-team.it/freno-a-mano-moza-hbp',
  },
  // Batch 4: Focus Sim Racing (Shopify, USD) — previously Instagram-only
  focussimracing: {
    'r5-bundle':    'https://focussimracing.com/products/moza-r5-bundle',
    'r9-v3-base':   'https://focussimracing.com/products/moza-r9-v3-direct-drive-wheel-base',
    'r12-base':     'https://focussimracing.com/products/moza-r12-v2-wheel-base',
    'r16-base':     'https://focussimracing.com/products/moza-r16-wheel-base-copy',
    'r21-base':     'https://focussimracing.com/products/moza-r16-wheel-base-v2-copy',
    'ks-wheel':     'https://focussimracing.com/products/moza-ks-steering-wheel',
    'cs-wheel':     'https://focussimracing.com/products/cs-v2p-steering-wheel',
    'cs-pro-wheel': 'https://focussimracing.com/products/moza-cs-pro-steering-wheel',
    'fsr2-wheel':   'https://focussimracing.com/products/fsr2-formula-wheel',
    'vision-gs':    'https://focussimracing.com/products/moza-vision-gs-wheel',
    'srp-pedals':   'https://focussimracing.com/products/moza-sr-p-pedal',
    'crp2-pedals':  'https://focussimracing.com/products/moza-crp2-pedals',
    'hgp-shifter':  'https://focussimracing.com/products/moza-hgp-shifter',
    'handbrake':    'https://focussimracing.com/products/moza-hbp-handbrake',
    'table-clamp':  'https://focussimracing.com/products/moza-table-clamp',
  },
  // Batch 4: VI PC Builder & Games (Shopify, CAD) — previously Instagram-only
  vipcbuilder: {
    'r5-bundle':    'https://vipcbuilder.ca/products/moza-racing-gm-rs20-r5-bundle-racing-simulator-retail',
    'r9-v3-base':   'https://vipcbuilder.ca/products/moza-racing-gm-rs080-r9-v3-direct-drive-wheel-base-retail',
    'r12-base':     'https://vipcbuilder.ca/products/moza-racing-gm-rs081-r12-v2-direct-drive-wheel-base-retail',
    'r21-base':     'https://vipcbuilder.ca/products/moza-racing-gm-rs033-r21-direct-drive-wheel-base-retail',
    'ks-wheel':     'https://vipcbuilder.ca/products/moza-racing-gm-rs047-ks-steering-wheel-retail',
    'cs-wheel':     'https://vipcbuilder.ca/products/moza-racing-gm-rs057-cs-v2p-steering-wheel-retail',
    'fsr2-wheel':   'https://vipcbuilder.ca/products/moza-racing-game-rs068-fsr-v2-formula-wheel-280mm-standard-4-3-display-retail',
    'srp-pedals':   'https://vipcbuilder.ca/products/moza-racing-gm-rs11-sr-p-two-pedals-retail',
    'hgp-shifter':  'https://vipcbuilder.ca/products/moza-racing-gm-rs039-hgp-shifter-retail-1',
    'handbrake':    'https://vipcbuilder.ca/products/moza-racing-gm-rs31-hbp-handbrake-retail-1',
  },
  // Batch 4: Pit Lane Sim Racing (Shopify, CAD) — previously Instagram-only
  pitlanesimracing: {
    'r5-bundle':    'https://pitlanesimracing.com/products/moza-racing-r5-sim-bundle-5-5-nm-torque-dd-and-srp-lite-pedals',
    'r9-v3-base':   'https://pitlanesimracing.com/products/moza-racing-r9-9-nm-direct-drive-wheel-base',
    'r12-base':     'https://pitlanesimracing.com/products/moza-racing-r12-12-nm-torque-direct-drive-wheel-base',
    'ks-wheel':     'https://pitlanesimracing.com/products/moza-racing-ks-steering-wheel',
    'gs-v2p-wheel': 'https://pitlanesimracing.com/products/moza-gs-v2p-gt-wheel',
    'fsr2-wheel':   'https://pitlanesimracing.com/products/moza-racing-fsr-formula-steering-wheel',
    'crp2-pedals':  'https://pitlanesimracing.com/products/moza-racing-crp2-2-pedal-set',
    'hgp-shifter':  'https://pitlanesimracing.com/products/moza-racing-hgp-shifter',
    'handbrake':    'https://pitlanesimracing.com/products/moza-racing-hbp-handbrake',
    'esx-wheel':    'https://pitlanesimracing.com/products/moza-racing-esx-steering-wheel',
    'table-clamp':  'https://pitlanesimracing.com/products/moza-racing-r9-wheel-table-clamp',
  },
  // Batch 5: Philippine expansion (May 2026) — Game One PH (Magento, PHP)
  gameone: {
    'r3-bundle':    'https://gameone.ph/moza-racing-r3-racing-wheel-and-pedals-for-pc-rs074.html',
    'r3-xbox':      'https://gameone.ph/moza-racing-r3-racing-wheel-and-pedals-for-xbox-series-x-s-xbox-one-windows-10-11-rs053.html',
    'r5-bundle':    'https://gameone.ph/moza-r5-racing-simulator-set-r5-dd-wheelbase-es-wheel-sr-p-lite-pedals-table-mount-rs20.html',
    'r5-truck':     'https://gameone.ph/moza-racing-r5-truck-driving-simulator-set-for-pc-rs071.html',
    'r9-v3-base':   'https://gameone.ph/moza-racing-r9-v3-direct-drive-wheel-base-rs080.html',
    'r12-base':     'https://gameone.ph/moza-racing-r12-v2-direct-drive-sim-racing-wheelbase.html',
    'cs-pro-wheel': 'https://gameone.ph/moza-racing-cs-pro-steering-wheel-rs093.html',
    'ks-pro-wheel': 'https://gameone.ph/moza-racing-ks-pro-steering-wheel-rs095.html',
    'ks-wheel':     'https://gameone.ph/moza-racing-ks-formula-steering-wheel-rs047.html',
    'rs-wheel':     'https://gameone.ph/moza-racing-rs-v2-steering-wheel-leather-rs25.html',
    'srp-pedals':   'https://gameone.ph/moza-racing-sr-p-racing-pedals-with-base-rs11.html',
    'crp2-pedals':  'https://gameone.ph/moza-crp2-racing-pedal-for-sim-racing-driving-video-games-rs066.html',
    'hgp-shifter':  'https://gameone.ph/moza-racing-hgp-shifter-rs039.html',
    'handbrake':    'https://gameone.ph/moza-racing-hbp-handbrake-rs31.html',
    'table-clamp':  'https://gameone.ph/moza-racing-table-mounting-bracket-rs12.html',
  },
  befastracing: {
    'r5-bundle':    'https://www.befastracing.com/products/r5-bundle-moza',
    'r12-base':     'https://www.befastracing.com/products/base-r12-moza',
    'ks-wheel':     'https://www.befastracing.com/products/volante-ks-moza',
    'srp-pedals':   'https://www.befastracing.com/products/pedales-sr-p-moza',
    'crp2-pedals':  'https://www.befastracing.com/products/crp2-pedals',
    'hgp-shifter':  'https://www.befastracing.com/products/palanca-hgp-shifter-h-7-r',
    'handbrake':    'https://www.befastracing.com/products/freno-de-mano-hbp-moza',
    'table-clamp':  'https://www.befastracing.com/products/table-clamp-moza',
  },
  // Batch 6: SE Asia & global expansion (May 2026) — Think of Sim (Shopify, THB)
  thinkofsim: {
    'r3-bundle':    'https://www.thinkofsim.com/products/moza-r3-racing-wheel-and-pedals-for-pc-only',
    'r3-xbox':      'https://www.thinkofsim.com/products/moza-r3-racing-wheel-and-pedals-for-xbox-pc',
    'r5-bundle':    'https://www.thinkofsim.com/products/moza-r5-es-wheel-bundle-with-srp-2-pedal',
    'r9-v3-base':   'https://www.thinkofsim.com/products/moza-r9-v3-wheel-base',
    'r12-base':     'https://www.thinkofsim.com/products/moza-r12-v2-direct-drive-wheel-base',
    'r21-base':     'https://www.thinkofsim.com/products/moza-r21-v2-wheel-base',
    'ks-wheel':     'https://www.thinkofsim.com/products/moza-ks-steering-wheel',
    'cs-v2p':       'https://www.thinkofsim.com/products/moza-cs-v2-steering-wheel',
    'gs-v2p-wheel': 'https://www.thinkofsim.com/products/moza-gs-v2-steering-wheel-leather-version',
    'rs-wheel':     'https://www.thinkofsim.com/products/moza-rs-v2-steering-wheel-leather',
    'vision-gs':    'https://www.thinkofsim.com/products/moza-rs064-vision-gs-wheel-streering',
    'fsr2-wheel':   'https://www.thinkofsim.com/products/moza-fsr2-formula-wheel',
    'esx-wheel':    'https://www.thinkofsim.com/products/moza-rs052-esx-steering-wheel-for-xbox',
    'tsw-wheel':    'https://www.thinkofsim.com/products/moza-tsw-truck-wheel',
    'srp-pedals':   'https://www.thinkofsim.com/products/moza-sr-p-2-pedal-with-base-plate',
    'crp2-pedals':  'https://www.thinkofsim.com/products/moza-moza-rs066-crp-2-pedals',
    'hgp-shifter':  'https://www.thinkofsim.com/products/moza-racing-hgp-shifter',
    'sgp-shifter':  'https://www.thinkofsim.com/products/moza-racing-sgp-sequential-shifter',
    'handbrake':    'https://www.thinkofsim.com/products/moza-hbp-handbrake',
    'table-clamp':  'https://www.thinkofsim.com/products/moza-rs12-table-clamp',
    // MOZA Flight
    'ab9-base':     'https://www.thinkofsim.com/products/moza-ab9-base',
    'mhg-stick':    'https://www.thinkofsim.com/products/moza-mhg-flightstick',
    'mh16-stick':   'https://www.thinkofsim.com/products/moza-mh16-flight-stick',
    'ma3x-stick':   'https://www.thinkofsim.com/products/moza-flight-ma3x-sidestick',
  },
  demontweeks: {
    'r3-bundle':    'https://www.demon-tweeks.com/uk/moza-r3-racing-wheel-and-pedal-for-pc-mzars074/',
    'r9-v3-base':   'https://www.demon-tweeks.com/uk/moza-r9-v3-direct-drive-wheel-base-mzars080/',
    'r12-base':     'https://www.demon-tweeks.com/uk/moza-r12-v2-direct-drive-wheel-base-mzars081/',
    'cs-wheel':     'https://www.demon-tweeks.com/uk/moza-cs-v2p-sim-racing-steering-wheel-mzars057/',
    'cs-pro-wheel': 'https://www.demon-tweeks.com/uk/moza-cs-pro-steering-wheel-mzars093/',
    'ks-pro-wheel': 'https://www.demon-tweeks.com/uk/moza-ks-pro-steering-wheel-mzars095/',
    'crp2-pedals':  'https://www.demon-tweeks.com/uk/moza-crp2-load-cell-sim-racing-pedals-mzars066/',
    'hgp-shifter':  'https://www.demon-tweeks.com/uk/moza-hgp-shifter-mzars039/',
    'handbrake':    'https://www.demon-tweeks.com/uk/moza-hpb-handbrake-mzars31/',
  },
  // Batch 6: SE Asia & global expansion — GGK Simracing (WooCommerce, THB)
  ggksimracing: {
    'r3-bundle':    'https://guidegamingkits.com/product/moza-racing-r3-bundle-set-%e0%b8%8a%e0%b8%b8%e0%b8%94%e0%b8%88%e0%b8%ad%e0%b8%a2%e0%b8%9e%e0%b8%a7%e0%b8%87%e0%b8%a1%e0%b8%b2%e0%b8%a5%e0%b8%b1%e0%b8%a2%e0%b8%a3%e0%b8%b0%e0%b8%9a%e0%b8%9a-direct-driv/',
    'r5-bundle':    'https://guidegamingkits.com/product/moza-racing-r5-simracing-moza-r5/',
    'r9-v3-base':   'https://guidegamingkits.com/product/moza-r9-v3-%e0%b8%9b%e0%b8%a3%e0%b8%b0%e0%b8%81%e0%b8%b1%e0%b8%99%e0%b8%a8%e0%b8%b9%e0%b8%99%e0%b8%a2%e0%b9%8c%e0%b9%84%e0%b8%97%e0%b8%a2-1-%e0%b8%9b%e0%b8%b5-direct-drive-9-nm-wheelbase-%e0%b8%88/',
    'r12-base':     'https://guidegamingkits.com/product/moza-racing-r12-direct-drive-wheelbase-%e0%b9%81%e0%b8%a3%e0%b8%87%e0%b8%9a%e0%b8%b4%e0%b8%94-12-nm-%e0%b8%9b%e0%b8%a3%e0%b8%b0%e0%b8%81%e0%b8%b1%e0%b8%99%e0%b8%a8%e0%b8%b9%e0%b8%99%e0%b8%a2%e0%b9%8c/',
    'r16-base':     'https://guidegamingkits.com/product/moza-r16-direct-drive-wheel-base-%e0%b8%88%e0%b8%ad%e0%b8%a2%e0%b8%9e%e0%b8%a7%e0%b8%87%e0%b8%a1%e0%b8%b2%e0%b8%a5%e0%b8%b1%e0%b8%a2-16-nm/',
    'r21-base':     'https://guidegamingkits.com/product/moza-r21-direct-drive-wheelbase-%e0%b8%88%e0%b8%ad%e0%b8%a2%e0%b8%9e%e0%b8%a7%e0%b8%87%e0%b8%a1%e0%b8%b2%e0%b8%a5%e0%b8%b1%e0%b8%a2-direct-drive-21-nm/',
    'r21-ultra':    'https://guidegamingkits.com/product/r21ultra/',
    'ks-wheel':     'https://guidegamingkits.com/product/moza-racing-ks-steering-wheel-%e0%b8%9b%e0%b8%a3%e0%b8%b0%e0%b8%81%e0%b8%b1%e0%b8%99%e0%b8%a8%e0%b8%b9%e0%b8%99%e0%b8%a2%e0%b9%8c-1-%e0%b8%9b%e0%b8%b5/',
    'cs-pro-wheel': 'https://guidegamingkits.com/product/moza-racing-cs-pro-steering-wheel/',
    'ks-pro-wheel': 'https://guidegamingkits.com/product/moza-racing-ks-pro-steering-wheel/',
    'gs-v2p-wheel': 'https://guidegamingkits.com/product/moza-gs-v2-steering-wheel/',
    'rs-wheel':     'https://guidegamingkits.com/product/moza-rsv2-steering-wheel-leather/',
    'vision-gs':    'https://guidegamingkits.com/product/moza-vision-gs-wheel-streering-%e0%b8%88%e0%b8%ad%e0%b8%a2%e0%b8%9e%e0%b8%a7%e0%b8%87%e0%b8%a1%e0%b8%b2%e0%b8%a5%e0%b8%b1%e0%b8%a2/',
    'tsw-wheel':    'https://guidegamingkits.com/product/moza-racing-tsw-truck-wheel-%e0%b8%9e%e0%b8%a7%e0%b8%87%e0%b8%a1%e0%b8%b2%e0%b8%a5%e0%b8%b1%e0%b8%a2%e0%b8%a3%e0%b8%96%e0%b8%9a%e0%b8%a3%e0%b8%a3%e0%b8%97%e0%b8%b8%e0%b8%81-%e0%b9%83%e0%b8%8a%e0%b9%89/',
    'srp-pedals':   'https://guidegamingkits.com/product/moza-sr-p-double-pedals/',
    'crp2-pedals':  'https://guidegamingkits.com/product/moza-racing-crp-clutch-pedal-%e0%b8%9b%e0%b8%a3%e0%b8%b0%e0%b8%81%e0%b8%b1%e0%b8%99%e0%b8%a8%e0%b8%b9%e0%b8%99%e0%b8%a2%e0%b9%8c%e0%b9%84%e0%b8%97%e0%b8%a2-1-%e0%b8%9b%e0%b8%b5/',
    'hgp-shifter':  'https://guidegamingkits.com/product/moza-hgp-shifter-%e0%b9%80%e0%b8%81%e0%b8%b5%e0%b8%a2%e0%b8%a3%e0%b9%8c-8-speed-7r-%e0%b8%9b%e0%b8%a3%e0%b8%b0%e0%b8%81%e0%b8%b1%e0%b8%99%e0%b8%a8%e0%b8%b9%e0%b8%99%e0%b8%a2%e0%b9%8c%e0%b9%84/',
    'sgp-shifter':  'https://guidegamingkits.com/product/moza-racing-sgp-sequential-shifter-%e0%b9%80%e0%b8%81%e0%b8%b5%e0%b8%a2%e0%b8%a3%e0%b9%8c-%e0%b8%9b%e0%b8%a3%e0%b8%b0%e0%b8%81%e0%b8%b1%e0%b8%99%e0%b8%a8%e0%b8%b9%e0%b8%99%e0%b8%a2%e0%b9%8c-1/',
    'handbrake':    'https://guidegamingkits.com/product/moza-racing-hbp-handbrake-%e0%b9%80%e0%b8%9a%e0%b8%a3%e0%b8%84%e0%b8%a1%e0%b8%b7%e0%b8%ad-analog-%e0%b8%9b%e0%b8%a3%e0%b8%b0%e0%b8%81%e0%b8%b1%e0%b8%99%e0%b8%a8%e0%b8%b9%e0%b8%99%e0%b8%a2%e0%b9%8c/',
    'table-clamp':  'https://guidegamingkits.com/product/moza-yoke-table-clamp-%e0%b9%81%e0%b8%84%e0%b8%a5%e0%b8%a1%e0%b8%9b%e0%b9%8c%e0%b8%a2%e0%b8%b6%e0%b8%94%e0%b9%82%e0%b8%95%e0%b9%8a%e0%b8%b0%e0%b8%aa%e0%b8%b3%e0%b8%ab%e0%b8%a3%e0%b8%b1/',
    // MOZA Flight
    'ab9-base':     'https://guidegamingkits.com/product/moza-ab9-base/',
    'mh16-stick':   'https://guidegamingkits.com/product/moza-mh16-flightstick-flight-sim-grip-%e0%b9%82%e0%b8%a5%e0%b8%ab%e0%b8%b0-27-%e0%b8%9b%e0%b8%b8%e0%b9%88%e0%b8%a1-%e0%b9%81%e0%b8%ae%e0%b8%97-8%e2%80%91%e0%b8%97%e0%b8%b4%e0%b8%a8-alumi/',
  },
  overclockersuk: {
    'r16-base':     'https://www.overclockers.co.uk/moza-racing-r16-v2-direct-drive-wheel-base-gam-moz-04850.html',
    'r21-base':     'https://www.overclockers.co.uk/moza-racing-r21-v2-direct-drive-wheel-base-gam-moz-04851.html',
    'rs-wheel':     'https://www.overclockers.co.uk/moza-racing-rs-v2-steering-wheel-round-leather-33-cm-rs25-gc-00t-mr.html',
    'srp-pedals':   'https://www.overclockers.co.uk/moza-racing-sr-p-load-cell-two-pedal-set-throttle-and-brake-black-rs11-gc-00a-mr.html',
    'vision-gs':    'https://www.overclockers.co.uk/moza-racing-vision-gs-steering-wheel-rs064-gam-moz-02864.html',
  },
  // Batch 6: Global expansion — SimRacing Store Chile (WooCommerce, CLP)
  simracingstore: {
    'r3-bundle':   'https://www.simracingstore.cl/tienda/bundle/kits-gama-entrada/volante-moza-r3-direct-drive-pc-b/',
    'r3-xbox':     'https://www.simracingstore.cl/tienda/bundle/kits-gama-entrada/volante-moza-r3-direct-drive-xbox-pc-b/',
    'r5-bundle':   'https://www.simracingstore.cl/tienda/bundle/kits-gama-entrada/bundle-volante-moza-r5-direct-drive-b/',
    'r5-truck':    'https://www.simracingstore.cl/tienda/bundle/kits-gama-entrada/simulador-de-camiones-moza-r5-b/',
    'r9-v3-base':  'https://www.simracingstore.cl/tienda/volantes/bases/base-direct-drive-moza-r9-v3-b/',
    'r12-base':    'https://www.simracingstore.cl/tienda/volantes/bases/volante-direct-drive-moza-r12-v2-b/',
    'ks-wheel':    'https://www.simracingstore.cl/tienda/volantes/manubrios/volante-formula-gt-moza-ks-b/',
    'cs-v2p':      'https://www.simracingstore.cl/tienda/volantes/manubrios/volante-moza-cs-v2p-b/',
    'gs-v2p-wheel':'https://www.simracingstore.cl/tienda/volantes/manubrios/volante-manubrio-para-pc-moza-gs-v2-b/',
    'rs-wheel':    'https://www.simracingstore.cl/tienda/volantes/manubrios/volante-manubrio-moza-rs-v2-b/',
    'fsr2-wheel':  'https://www.simracingstore.cl/tienda/volantes/manubrios/volante-formula-1-moza-fsr2-b/',
    'esx-wheel':   'https://www.simracingstore.cl/tienda/volantes/manubrios/manubrio-xbox-pc-moza-esx-b/',
    'tsw-wheel':   'https://www.simracingstore.cl/tienda/volantes/manubrios/volante-camion-moza-tsw-b/',
    'table-clamp': 'https://www.simracingstore.cl/tienda/volantes/bases/soporte-para-mesa-o-escritorio-moza-r9/',
    'ab9-base':    'https://www.simracingstore.cl/tienda/volantes/bases/base-direct-drive-moza-ab9-b/',
    'mfy-yoke':    'https://www.simracingstore.cl/tienda/simulador-de-vuelo/volante-vuelo-moza-mfy-yoke/',
    'ay210-yoke':  'https://www.simracingstore.cl/tienda/volantes/bases/base-direct-drive-ay210-vuelo/',
    'cm2-dash':    'https://www.simracingstore.cl/tienda/otros-accesorios/diplays-botoneras/pantalla-moza-dash-cm2-hd/',
  },
  // Batch 6: Global expansion — Megabike Plus Czech (WooCommerce, CZK)
  megabikeplus: {
    'r3-bundle':   'https://www.megabikeplus.cz/volanty/moza-r3-kompletni-sada/',
    'r5-bundle':   'https://www.megabikeplus.cz/volanty/moza-r5-kompletni-sada/',
    'r9-v3-base':  'https://www.megabikeplus.cz/volanty/moza-r9-v3/',
    'r12-base':    'https://www.megabikeplus.cz/volanty/moza-r12/',
    'r16-base':    'https://www.megabikeplus.cz/volanty/moza-r16-v2/',
    'r21-base':    'https://www.megabikeplus.cz/volanty/moza-r21/',
    'ks-wheel':    'https://www.megabikeplus.cz/volanty/moza-ks/',
    'cs-v2p':      'https://www.megabikeplus.cz/volanty/moza-cs-v2/',
    'gs-v2p-wheel':'https://www.megabikeplus.cz/volanty/moza-gs-v2/',
    'rs-wheel':    'https://www.megabikeplus.cz/volanty/moza-rs-v2/',
    'fsr2-wheel':  'https://www.megabikeplus.cz/volanty/moza-fsr2/',
    'srp-pedals':  'https://www.megabikeplus.cz/volanty/moza-sr-p/',
    'hgp-shifter': 'https://www.megabikeplus.cz/volanty/moza-hgp/',
    'handbrake':   'https://www.megabikeplus.cz/volanty/moza-hbp/',
  },
};

function buildUrlEntries() {
  var entries = [];
  for (var retailerId in PRODUCT_URLS) {
    var products = PRODUCT_URLS[retailerId];
    for (var productId in products) {
      entries.push({ url: products[productId], retailerId: retailerId, productId: productId });
    }
  }
  return entries;
}

// MSRP in USD from MOZA official store (mozaracing.com)
const MSRP_MAP = {
  // MOZA Racing
  'r3-bundle':    349,
  'r5-bundle':    599,
  'r9-bundle':    799,
  'r9-v3-base':   499,
  'r12-base':     499,
  'r16-base':     659,
  'r21-base':     999,
  'es-wheel':     99,
  'esx-wheel':    149,
  'ks-wheel':     199,
  'ks-pro-wheel': 349,
  'cs-wheel':     249,
  'cs-pro-wheel': 349,
  'gs-v2p-wheel': 399,
  'rs-wheel':     399,
  'fsr2-wheel':   599,
  'vision-gs':    699,
  'srp-lite':     79,
  'srp-pedals':   199,
  'crp-pedals':   349,
  'crp2-pedals':  399,
  'hgp-shifter':  159,
  'handbrake':    109,
  'table-clamp':  49,
  // MOZA Flight (飞模)
  'ab6-bundle':   399,
  'ab9-base':     549,
  'mhg-stick':    99,
  'mh16-stick':   169,
  'ma3x-stick':   79,
  'ay210-yoke':   848,
  'mtq-throttle': 199,
  'mtp-throttle': 329,
  'mtlp-panel':   149,
  'mrp-pedals':   349,
};

module.exports = { PRODUCTS, RETAILERS, PRODUCT_URLS, MSRP_MAP, buildUrlEntries };
